### ISSUE TITLE
win 10 安装 node v6.10.2 安装报错

### ISSUE THREAD

**Issue by macowin** [apache/incubator-weex-cli#103]
网上说 是按依赖 fsevents  出错,只用于mac 机 如何 让按装不包含 fsevents 呢？
`C:\Users\Administrator>cnpm install -g weex-toolkit
Downloading weex-toolkit to C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit_tmp
Copying C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit_tmp\._weex-toolkit@1.0.5@weex-toolkit to C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit
Installing weex-toolkit's dependencies to C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit/node_modules
[1/10] weex-components@^0.2.0 installed at node_modules\._weex-components@0.2.0@weex-components
[2/10] chalk@^1.1.3 installed at node_modules\._chalk@1.1.3@chalk
[3/10] opener@^1.4.1 installed at node_modules\._opener@1.4.3@opener
[4/10] fs-extra@^2.0.0 installed at node_modules\._fs-extra@2.1.2@fs-extra
[5/10] npmlog@^4.0.0 installed at node_modules\._npmlog@4.0.2@npmlog
[6/10] prompt@^1.0.0 installed at node_modules\._prompt@1.0.0@prompt
[7/10] xtoolkit@^0.2.1 installed at node_modules\._xtoolkit@0.2.7@xtoolkit
[8/10] yargs@^6.6.0 installed at node_modules\._yargs@6.6.0@yargs
[9/10] weex-previewer@^1.3.3 installed at node_modules\._weex-previewer@1.3.7@weex-previewer
fsevents@1.1.1 download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://npm.taobao.org/mirrors/fsevents"}
platform unsupported weex-builder@0.2.6 › webpack@1.15.0 › watchpack@0.2.9 › chokidar@1.6.1 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
[10/10] weex-builder@^0.2.3 installed at node_modules\._weex-builder@0.2.6@weex-builder
execute post install 3 scripts...
[1/3] scripts.postinstall xtoolkit@0.2.7 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@^1.0.15 run "node postinstall"
[1/3] scripts.postinstall xtoolkit@0.2.7 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@^1.0.15 finished in 153ms[2/3] scripts.postinstall xtoolkit@^0.2.1 run "node ./src/hook/post_install.js"
ping  http://registry.npm.taobao.org : 36
ping  http://registry.npmjs.org : timeout
[2/3] scripts.postinstall xtoolkit@^0.2.1 finished in 5s
[3/3] scripts.postinstall weex-previewer@^1.3.3 run "node ./src/hook/post-install.js"
[3/3] scripts.postinstall weex-previewer@^1.3.3 finished in 367ms
deprecate weex-previewer@1.3.7 › quick-local-ip@1.0.7 › mocha@2.5.3 › to-iso-string@0.0.2 to-iso-string has been deprecated, use @segment/to-iso-string instead.
deprecate weex-previewer@1.3.7 › quick-local-ip@1.0.7 › mocha@2.5.3 › jade@0.26.3 Jade has been renamed to pug, please install the latest version of pug instead of jade
deprecate weex-previewer@1.3.7 › quick-local-ip@1.0.7 › mocha@2.5.3 › glob@3.2.11 › minimatch@0.3 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Recently updated (since 2017-04-08): 9 packages (detail see file C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\.recently_updates.txt)
  Today:
    → weex-builder@0.2.6 › css-loader@0.26.4 › cssnano@3.10.0 › autoprefixer@6.7.7 › caniuse-db@^1.0.30000634 (11:45:50)
  2017-04-14
    → weex-builder@0.2.6 › css-loader@0.26.4 › postcss@^5.0.6 (06:57:58)
    → yargs@6.6.0 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › normalize-package-data@2.3.6 › hosted-git-info@^2.1.4 (06:54:59)
    → weex-previewer@1.3.7 › weex-vue-render@^0.11.2 (18:03:07)
    → weex-builder@0.2.6 › webpack@1.15.0 › watchpack@0.2.9 › chokidar@1.6.1 › anymatch@1.3.0 › micromatch@2.3.11 › arr-diff@2.0.0 › arr-flatten@^1.0.1 (19:28:16)
  2017-04-13
    → weex-builder@0.2.6 › webpack@^1.13.1 (18:20:18)
  2017-04-10
    → weex-builder@0.2.6 › vue-loader@10.3.0 › vue-template-es2015-compiler@^1.2.2 (09:49:37)
    → weex-builder@0.2.6 › weex-loader@0.4.4 › weex-scripter@0.1.5 › browserify@13.0.1 › crypto-browserify@3.11.0 › browserify-sign@4.0.4 › elliptic@6.4.0 › hmac-drbg@^1.0.0 (06:33:31)
  2017-04-09
    → weex-builder@0.2.6 › css-loader@0.26.4 › cssnano@3.10.0 › autoprefixer@6.7.7 › browserslist@1.7.7 › electron-to-chromium@^1.2.7 (03:35:27)
All packages installed (603 packages installed from npm registry, used 34s, speed 452.69kB/s, json 687(1.08MB), tarball 13.86MB)
[weex-toolkit@1.0.5] link C:\Users\Administrator\AppData\Roaming\npm\weex@ -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex

C:\Users\Administrator>weex
C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\package\NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\._weex-previewer
    at NpmPackage.resolve (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\package\NpmPackage.js:50:23)
    at Command.run (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\Command.js:43:13)
    at XToolkit._done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\xtoolkit.js:149:36)
    at process.nextTick (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3`

**Comment by JackPu** [comment]
用 `npm install -g toolkit`吧
