### ISSUE TITLE
Babel build error

### ISSUE THREAD

**Issue by Modcat** [apache/incubator-weex-cli#105]
Hi,

Thank you so much for your development for VueJS and app layer. It is a really amazing product you have here! However when following the exact instructions and using admin privileges and a combination of things I get the following error

Steps I followed:

    NodeJS 6.10
    sudo npm install -g weex-toolkit
    weex create myApp
    cd myApp && npm install
    weex platform add ios android
    sudo weex build ios

Error...

`ERROR in ./temp?entry=true
Module build failed: Error: Couldn't find preset "latest" relative to directory "/Users/lawrenceturton/Desktop"
    at /Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/lawrenceturton/Desktop/myApp/node_modules/babel-loader/lib/index.js:46:20)
 @ multi (webpack)-dev-server/client?http://192.168.0.4:8080/web ./temp?entry=true
`

Kind regards, Lawrence

**Comment by erha19** [comment]
Hi,

Sorry I haven’t got back to you sooner.

I found that this is some of the old version of the problem, in the latest version has been fixed, you can try to upgrade the following order your `weex-toolkit`:
```
npm i weex-toolkit -g
```
If there is a problem with permissions, we suggest you run `sudo chmod 777 ~` or `mkdir ~/.xtoolkit&chmod 777 .xtoolkit`.

If there is an old version of the conflict during the installation process, you need to run the command like this and make sure your npm is a newer version:
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weex-devtool
```
Best regards, Erha19
