### ISSUE TITLE
enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/weex-toolkit/node_modules/abbrev'

### ISSUE THREAD

**Issue by KClassmate** [apache/incubator-weex-cli#120]
npm ERR! path /usr/local/lib/node_modules/weex-toolkit/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/weex-toolkit/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ksy-ios/.npm/_logs/2017-05-19T07_10_43_000Z-debug.log

node -v
v7.10.0
npm -v
4.6.1

换成cnpm 就是
/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/_weex-previewer
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50:23)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:149:36)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
我还改了权限 也是不行 
drwxrwxrwx  8 root     wheel  272  5 19 15:09 node_modules
有碰到的吗？

**Comment by WangYang-Rex** [comment]
同问

**Comment by agoodcoolman** [comment]
同样的问题，我也是

**Comment by QiuLiangXiong** [comment]
同问

**Comment by Lorem3** [comment]
?没人维护?

**Comment by JackPu** [comment]
@m18210875071  请提供下npm 和 node版本号以及你的操作系统？

**Comment by WangYang-Rex** [comment]
已解决：先npm uninstall weex-toolkit,然后用npm install -g weex-toolkit下载，不要用cnpm，最好可以翻墙

**Comment by erha19** [comment]
You can try:
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weex-devtool
```
Remember to update your npm version and do not use cnpm to install the package.

**Comment by Rensdn** [comment]
no such file or directory, access '/usr/local/lib/node_modules/appdmg/node_modules/array-buffer-from-string'

**Comment by cy920820** [comment]
no such file or directory, access '/Users/cuiyang/.nvm/versions/node/v9.11.1/lib/node_modules/weex-toolkit/node_modules/abbrev'
