### ISSUE TITLE
安装报错。

### ISSUE THREAD

**Issue by xuanhen2013** [apache/incubator-weex-cli#123]
````
▶ npm install -g weex-toolkit
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/xxx/.nvm/versions/node/v6.10.3/bin/weex -> /Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/bin/weex

> fsevents@1.1.1 install /Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/fsevents
> node install

[fsevents] Success: "/Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> spawn-sync@1.0.15 postinstall /Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall


> weex-previewer@1.3.8 postinstall /Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/Users/xxx"

> xtoolkit@0.2.7 postinstall /Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/xtoolkit
> node ./src/hook/post_install.js

ping  http://registry.npm.taobao.org : 31.128
ping  http://registry.npmjs.org : 59.643
fs.js:641
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^

Error: EACCES: permission denied, open '/Users/xxx/.xtoolkit/config.json'
at Error (native)
at Object.fs.openSync (fs.js:641:18)
at Object.fs.writeFileSync (fs.js:1347:33)
at Object.exports.save (/Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/config.js:41:8)
at done (/Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/hook/post_install.js:24:20)
at ChildProcess.onEnd (/Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/ping.js:97:9)
at ChildProcess.<anonymous> (/Users/xxx/.nvm/versions/node/v6.10.3/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/ping.js:81:40)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
  /Users/xxx/.nvm/versions/node/v6.10.3/lib
  └── (empty)

  npm ERR! Darwin 16.6.0
  npm ERR! argv "/Users/xxx/.nvm/versions/node/v6.10.3/bin/node" "/Users/xxx/.nvm/versions/node/v6.10.3/bin/npm" "install" "-g" "weex-toolkit"
  npm ERR! node v6.10.3
  npm ERR! npm  v3.10.10
  npm ERR! code ELIFECYCLE

  npm ERR! xtoolkit@0.2.7 postinstall: `node ./src/hook/post_install.js`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the xtoolkit@0.2.7 postinstall script 'node ./src/hook/post_install.js'.
  npm ERR! Make sure you have the latest version of node.js and npm installed.
  npm ERR! If you do, this is most likely a problem with the xtoolkit package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     node ./src/hook/post_install.js
  npm ERR! You can get information on how to open an issue for this project with:
  npm ERR!     npm bugs xtoolkit
  npm ERR! Or if that isn't available, you can get their info via:
  npm ERR!     npm owner ls xtoolkit
  npm ERR! There is likely additional logging output above.

  npm ERR! Please include the following file with any support request:
  npm ERR!     /Users/xxx/npm-debug.log
  npm ERR! code 1
````
然后我打开 `~/.xtoolkit` 目录，目录下根本没有 `config.json` 文件
什么情况？SS翻墙下载的

**Comment by JackPu** [comment]
@LoveJune2014  `sudo chmod -R 777 /Users/xxx/`

**Comment by erha19** [comment]
see #137
