### ISSUE TITLE
执行weex -h报错

### ISSUE THREAD

**Issue by s249359986** [apache/incubator-weex-cli#141]
使用sudo npm install weex-toolkit，安装成功,执行weex -h报下面错误.

/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/._weex-previewer
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50:23)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:149:36)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by erha19** [comment]
The version 1.0.9 of weex-toolkit has fixed this bug.
