### ISSUE TITLE
weex debug 错误

### ISSUE THREAD

**Issue by s249359986** [apache/incubator-weex-cli#142]
1.weex debug 提示This command need to install weex-devtool. Install now?
2.选择y安装后提示必须使用 sudo安装。
3sudo weex debug 再安装weex-devtool时报以下错误：
{ AssertionError [ERR_ASSERTION]: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
    at Command.immediateStart (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.1.7@xtoolkit/src/Command.js:49:9)
    at Locator.getInstance.locate.then (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.1.7@xtoolkit/src/Command.js:30:29)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
AssertionError [ERR_ASSERTION]: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
    at Command.immediateStart (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.1.7@xtoolkit/src/Command.js:49:9)
    at Locator.getInstance.locate.then (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.1.7@xtoolkit/src/Command.js:30:29)
    at <anonymous>

**Comment by erha19** [comment]
Try:
```
rm -rf ~/.xtoolkit
npm update npm -g
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weex-devtool
```
