### ISSUE TITLE
weex debug 报错

### ISSUE THREAD

**Issue by JohnKKK9** [apache/incubator-weex-cli#151]
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/KKK/.xtoolkit/node_modules/weex-devtool/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at NpmPackage.findBinPath (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:58:41)
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:27:46)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/xtoolkit.js:141:33)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by JohnKKK9** [comment]
升级npm到最新版之后debug成功
