### ISSUE TITLE
运行weex报错

### ISSUE THREAD

**Issue by mario-huang** [apache/incubator-weex-cli#155]
$ weex src/pages/module_one/one/App.vue
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/xxx/.weex_tmp/app.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.replace (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/libs/helper.js:22:22)
    at Object.createVueAppEntry (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:101:12)
    at Object.buildJSFile (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:124:12)
    at Object.fileFlow (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:65:10)
    at Object.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:59:17)
    at module.exports (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:186:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/bin/weex-previewer:63:1)

**Comment by erha19** [comment]
You can reinstall your weex-toolkit like this:
```
npm i npm@5 -g
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
```
If you also have some error, please tell me you npm version and weex version use `npm -v & weex-v`
