### ISSUE TITLE
关于版本升级

### ISSUE THREAD

**Issue by jamesmaxwell** [apache/incubator-weex-cli#160]
好好的在测试，忽然提醒我升级：
```
Update available 1.3.12 → 1.3.13                 
Run weex update weex-previewer@1.3.13 to update
```
我手贱就升级了。于是就悲剧了，执行 weex  xxx.vue 的时候报找不到  ‘weex-builder'
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'weex-builder'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v7.9.0/lib/node_modules/weex-toolkit/bin/weex:56:63)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
```
我很无奈，没升级前还好好的 :(
于是想找一下到底升级了什么，还是很无奈，啥也没有 :(
然后我想可能 weex-toolkit 也升级了，果然最新是 v1.1.0 了，升级完后， 错误变成了下面这样：
```
/Users/xxx/.nvm/versions/node/v7.9.0/lib/node_modules/weex-toolkit/node_modules/_webpack@1.15.0@webpack/lib/TemplatedPathPlugin.js:50
			if(!allowEmpty) throw new Error("Path variable " + match + " not implemented in this context: " + input);
			                ^

Error: Path variable [name] not implemented in this context: /Users/xxx/.weex_tmp/[name].weex.js
    at /Users/xxx/.nvm/versions/node/v7.9.0/lib/node_modules/weex-toolkit/node_modules/_webpack@1.15.0@webpack/lib/TemplatedPathPlugin.js:50:26
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at MainTemplate.replacePathVariables (/Users/xxx/.nvm/versions/node/v7.9.0/lib/node_modules/weex-toolkit/node_modules/_webpack@1.15.0@webpack/lib/TemplatedPathPlugin.js:73:4)
....
```
一阵心凉啊

意见以后升级版本时写个升级说明，谢谢了。

**Comment by erha19** [comment]
Sorry this is my problem, you can try to solve by following method：
```
weex update weex-previewer@latest
```

**Comment by JustLikeU** [comment]
`➜ weex update weex-previewer@latest
module.js:529
    throw err;
    ^

Error: Cannot find module 'xtoolkit'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/bin/weex:2:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)`

我也遇到那样的问题，然后更新最新版本的weex-previewer报错
再输入任何weex命令，就出现以上错误了。

**Comment by huang1988519** [comment]
额，同样碰到了
```
odule.js:538
    throw err;
    ^

Error: Cannot find module 'weex-previewer'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/bin/weex.js:40:59)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

因为更新后，只要执行 'weex` 命令就报错。所以上面说的  `weex update weex-previewer@latest` 无法成功执行。

**Comment by huang1988519** [comment]
重装 weex，再此提示 
```
                 Update available 1.3.13-beta.10 → 1.3.13-beta.12          │
   │   Run weex update weex-previewer@1.3.13-beta.12 to update
```
时执行
```
weex update weex-previewer@latest`
```
