### ISSUE TITLE
Error: Path variable [name] not implemented in this context

### ISSUE THREAD

**Issue by hizhengfu** [apache/incubator-weex-cli#170]
weex info
```bat
v1.1.0-beta.2
 - weexpack : v0.4.7-beta.8
 - weex-builder : v0.2.13-beta.2
 - weex-previewer : v1.3.13
```
``` bat
$ weex ./src/index.vue 
Error: Path variable [name] not implemented in this context: /Users/xxx/.weex_tmp/[name].weex.js
    at /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/TemplatedPathPlugin.js:50:26
    at String.replace (<anonymous>)
    at MainTemplate.replacePathVariables (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/TemplatedPathPlugin.js:73:4)
    at MainTemplate.applyPlugins [as applyPluginsWaterfall] (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/tapable/lib/Tapable.js:37:47)
    at Compilation.getPath (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/Compilation.js:882:27)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/Compiler.js:228:28)
    at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.emitAssets (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/Compiler.js:54:18)
    at /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/Compiler.js:403:12
info Sun Oct 15 2017 18:29:16 GMT+0800 (CST)WebSocket  is listening on port 8082 
info Sun Oct 15 2017 18:29:16 GMT+0800 (CST)http  is listening on port 8081 
info http://192.168.16.166:8081/?hot-reload_controller&page=index.js&loader=xhr&wsport=8082&type=vue 

```

**Comment by hizhengfu** [comment]
看起来是weex-previewer版本问题，但是更新到latest发现weex-toolkit不能用了。
```bat
$ weex -v
module.js:529
    throw err;
    ^

Error: Cannot find module 'weex-builder'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/bin/weex:56:63)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)

```

**Comment by erha19** [comment]
Maybe you have some errors during the installation process, you can re-install by following method:
Do not use `cnpm` and make sure your npm version >= 5.0.
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weex-previewer@latest
```

**Comment by hizhengfu** [comment]
没有使用cnpm，也使用过上述手段修复。
正常安装weex-toolkit 后运行 weex ./xxx.vue 出现 Error: Path variable [name] not implemented in this context:
对比使用的版本weex-previewer应该为v1.3.13-beta.3 而不是v1.3.13
手工更新
weex update weex-previewer@latest 后再运行weex会出现Error: Cannot find module 'weex-builder'

出现上面错误时，直接安装到全局 npm install -g weex-builder 可以正常使用。应该是weex update依赖关系有问题。

**Comment by erha19** [comment]
Emmm...that's strange

Are you developing on the window or mac? 

I will collect this issue and fix it in a later version.

**Comment by hizhengfu** [comment]
本机环境：
mac high sierra
node:v8.7.0
npm:5.4.2

**Comment by xwg2015** [comment]
我也是mac 遇到跟你一样的问题
![image](https://user-images.githubusercontent.com/19931311/31653662-f73bfc6e-b2e8-11e7-85bd-5ce176c47a8a.png)

**Comment by erha19** [comment]
@JustLikeU please show me your weex version, try to update `weex-previewer` to `v1.3.13-beta.5`.
```
weex update weex-previewer
```

**Comment by xwg2015** [comment]
@erha19
```shell
➜ weex --version
   v1.1.0-beta.2
 - weexpack : v0.4.7-beta.8
 - weex-builder : v0.2.13-beta.2
 - weex-previewer : v1.3.13
```

**Comment by xwg2015** [comment]
@erha19 
after updating weex-previewer
```shell
# ~/Documents/weex/buxingjie [17:30:14]
➜ sudo weex update weex-previewer
Password:
? update package "weex-previewer" now? Yes

# ~/Documents/weex/buxingjie [17:30:41]
➜ sudo weex src --entry src/index.vue
module.js:529
    throw err;
    ^

Error: Cannot find module 'weex-builder'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/xwg/.nvm/versions/node/v8.7.0/lib/node_modules/weex-toolkit/bin/weex:56:63)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by erha19** [comment]
@JustLikeU Try `npm install -g weex-builder`, same issue.

**Comment by xwg2015** [comment]
@erha19 
thank you! Problem solved.

**Comment by liangklfang** [comment]
How you solved it?@JustLikeU

**Comment by xwg2015** [comment]
@liangklfang Try `npm install -g weex-builder`
