### ISSUE TITLE
mac电脑安装失败

### ISSUE THREAD

**Issue by lisa0606** [apache/incubator-weex-cli#173]
执行了：`sudo npm install -g weex-toolkit`
系统：Mac 10.11.6 (15G1611)
Node： v8.0.0/v8.7.0/v7.10.1
搞了两天实在不行才来这里求助的

```
lisa0606:xtoolkit lisa0606$ sudo npm install -g weex-toolkit
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex.js

> fsevents@1.1.2 install /usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.1.2 install /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.1.2 install /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.1.2 install /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/spawn-sync
> node postinstall


> xtoolkit@0.2.10 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit
> node ./src/hook/post_install.js

ping  http://registry.npm.taobao.org : 28.809
ping  http://registry.npmjs.org : 168.902
fs.js:638
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/Users/lisa0606/.xtoolkit/config.json'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.writeFileSync (fs.js:1287:33)
    at Object.exports.save (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/config.js:43:6)
    at done (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/hook/post_install.js:23:14)
    at ChildProcess.onEnd (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/ping.js:95:5)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/ping.js:81:36)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rx@4.1.0 (node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/rx):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of input at 1:32895
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: li":"*","grunt":"*","grunt-contrib-jshint":"*","grunt-contrib-connect
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:                                                                      ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cssnano@3.10.0 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/cssnano):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of input at 1:46584
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browser":"^0.5.3","tap-spec":"^4.1.0","tape":"^4.2.2","webpack":"^1.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:                                                                      ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: es5-ext@0.10.30 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/es5-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of input at 1:15577
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: m.taobao.org/es5-ext/download/es5-ext-0.9.0.tgz"},"engines":{"node":"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:                                                                      ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cssnano@3.10.0 (node_modules/weex-toolkit/node_modules/weex-builder/node_modules/cssnano):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of input at 1:46584
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browser":"^0.5.3","tap-spec":"^4.1.0","tape":"^4.2.2","webpack":"^1.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:                                                                      ^

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xtoolkit@0.2.10 postinstall: `node ./src/hook/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xtoolkit@0.2.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lisa0606/.npm/_logs/2017-10-17T14_29_19_831Z-debug.log
```

**Comment by lisa0606** [comment]
用cnpm装成功了
