### ISSUE TITLE
执行weex src/index.vue打开的网页中，查看文件源码显示找不到网页，同时playground扫码无结果

### ISSUE THREAD

**Issue by yuzai** [apache/incubator-weex-cli#175]
环境：
windows,node -v v6.11.4，npm -v
5.5.1
 weex -v
   v1.1.0-beta.4
 - weexpack : v0.4.7-beta.9
 - weex-builder : v0.2.13-beta.2
 - weex-previewer : v1.3.13

问题：
手机和pc在同一个局域网内，扫码无结果，点击页面上的查看文件源码之后也是空的,npm run dev和npm run serve是没有问题的。
![image](https://user-images.githubusercontent.com/16518346/31711361-6e96e48a-b42a-11e7-9b27-b003f16867b8.png)
点击图片中的查看文件源代码出现下图：
![image](https://user-images.githubusercontent.com/16518346/31711396-82c1f454-b42a-11e7-8500-37cf051b4ccf.png)
控制台执行weex src/index.vue的时候报错：
Error: Path variable [name] not implemented in this context: C:\Users\xiaoboma\.weex_tmp/[name].weex.js
    at C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\webpack\lib\TemplatedPathPlugin.js:50:26
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Template.replacePathVariables (C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\webpack\lib\TemplatedPathPlugin.js:73:4)
    at Template.applyPlugins [as applyPluginsWaterfall] (C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\tapable\lib\Tapable.js:37:47)
    at Compilation.getPath (C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\webpack\lib\Compilation.js:882:27)
    at Compiler.<anonymous> (C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\webpack\lib\Compiler.js:228:28)
    at Compiler.applyPluginsAsync (C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.emitAssets (C:\Users\xiaoboma\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\webpack\lib\Compiler.js:226:7)
info Wed Oct 18 2017 17:37:15 GMT+0800 (中国标准时间)WebSocket  is listening on port 8082
info Wed Oct 18 2017 17:37:15 GMT+0800 (中国标准时间)http  is listening on port 8081
info http://10.170.48.103:8081/?hot-reload_controller&page=index.js&loader=xhr&wsport=8082&type=vue

**Comment by yuzai** [comment]
https://github.com/alibaba/weex-ui/issues/10
这个issue中指出weex-preview@1.3.13存在这个问题，可以选择降级或者升级到最新的版本都可以修复这个问题。
现在最新的weex-toolkit@1.1.0-beta5已经修改了weex-previewer的版本，改成最新的
所以uninstall再install weex-toolkit就可以解决这个问题了

**Comment by AugTang** [comment]
怎么解决，还是没用 @yuzai

**Comment by yuzai** [comment]
我的问题就只是版本的问题。。。不懂，你可以开个issus把版本粘上去再问问
