### ISSUE TITLE
weex create project failed?  

### ISSUE THREAD

**Issue by 1gehunzi** [apache/incubator-weex-cli#177]
weex -v                                                                      
   v1.1.0-beta.5
 - weexpack : v0.4.7-beta.13
 - weex-builder : v0.2.13-beta.4
 - weex-previewer : v1.3.13-beta.7

  node -v                                                                   
v8.4.0
npm -v
5.3.0

weex create demo                                                            
This command need to install weexpack. Installing...
/Users/.xtoolkit/node_modules/weexpack/node_modules/q/q.js:126
                    throw e;
                    ^

Error: spawn E2BIG
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at UpdateNotifier.check (/Users/.xtoolkit/node_modules/weexpack/node_modules/update-notifier/index.js:64:2)
    at module.exports (/Users/.xtoolkit/node_modules/weexpack/node_modules/update-notifier/index.js:124:17)
    at checkForUpdates (/Users/.xtoolkit/node_modules/weexpack/build/cli.js:68:20)
    at cli (/Users/.xtoolkit/node_modules/weexpack/build/cli.js:218:3)
    at /Users//.xtoolkit/node_modules/weexpack/build/cli.js:111:12
    at _fulfilled (/Users/.xtoolkit/node_modules/weexpack/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/User/.xtoolkit/node_modules/weexpack/node_modules/q/q.js:816:30)
----------------

**Comment by erha19** [comment]
see #178

**Comment by 1gehunzi** [comment]
thx~
