### ISSUE TITLE
weex create project error

### ISSUE THREAD

**Issue by Zxg444363021** [apache/incubator-weex-cli#178]
E:\Weex Projects>weex -v
   v1.1.0
 - weexpack : v0.4.7-beta.13
 - weex-builder : v0.2.12
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13

E:\Weex Projects>weex create myFirstProject
C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\q\q.js:126
                    throw e;
                    ^

Error: spawn ENAMETOOLONG
    at _errnoException (util.js:1019:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:494:9)
    at UpdateNotifier.check (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\update-notifier\index.js:64:2)
    at module.exports (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\update-notifier\index.js:124:17)
    at checkForUpdates (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\build\cli.js:68:20)
    at cli (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\build\cli.js:218:3)
    at C:\Users\Administrator\.xtoolkit\node_modules\weexpack\build\cli.js:111:12
    at _fulfilled (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\q\q.js:816:30)

**Comment by erha19** [comment]
This is a bug on weexpack, latest version has fixed it, see https://github.com/weexteam/weex-toolkit#spawn-e2big.
