### ISSUE TITLE
Fails at npm run serve 

### ISSUE THREAD

**Issue by kallevu** [apache/incubator-weex-cli#187]
node: 8.9.1
npm: 5.5.1
weex-toolkit: 1.1.0-beta.7
osx: 10.12.6

1. `npm install -g weex-toolkit`
2. `weex create myproject`
3. `cd myproject`
4. `npm install`
5. `npm run build`
6. `npm run serve`

```
> weex@1.0.0 serve /Users/___/git/weex/myproject
> webpack-dev-server --config webpack.dev.js --watch --open

server is running! Please open http://MY_IP:8080/
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weex@1.0.0 serve: `webpack-dev-server --config webpack.dev.js --watch --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kallevu** [comment]
arrr, other app was using same port.
