### ISSUE TITLE
Trying to update my tools, but I can't

### ISSUE THREAD

**Issue by marquesm91** [apache/incubator-weex-cli#191]
```
matheus@matheus-pc:~/work/awesome-project$ weex update weexpack
? update package "weexpack" now? (Y/n) 

/usr/lib/node_modules/weex-toolkit/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 0.22
    at new SemVer (/usr/lib/node_modules/weex-toolkit/node_modules/semver/semver.js:293:11)
    at SemVer (/usr/lib/node_modules/weex-toolkit/node_modules/semver/semver.js:286:12)
    at /usr/lib/node_modules/weex-toolkit/node_modules/check-node-version/index.js:113:33
    at module.exports (/usr/lib/node_modules/weex-toolkit/node_modules/map-values/index.js:9:18)
    at /usr/lib/node_modules/weex-toolkit/node_modules/check-node-version/index.js:106:20
    at end (/usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:16:15)
    at done (/usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:20:10)
    at each (/usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:26:7)
    at /usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:36:43
    at /usr/lib/node_modules/weex-toolkit/node_modules/check-node-version/index.js:53:14
```

I keep getting this output. Am I doing something wrong?

**Comment by erha19** [comment]
Please provide your local environment, like npm version and weex version, thanks!
I guess your `weex-toolkit` version is too old, try the command below:
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weexpack
```

**Comment by marquesm91** [comment]
OS: Ubuntu 16.04 LTS Xenial
npm version: 5.5.1
node version: 6.11.4
When I tried to get weex version I got this:

```
matheus@matheus-pc:~/work/vue-async$ weex -v
   v1.1.0-beta.7
 - weex-builder : v0.2.13-beta.4
 - weex-previewer : v1.3.13-beta.10
/usr/lib/node_modules/weex-toolkit/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 0.22
    at new SemVer (/usr/lib/node_modules/weex-toolkit/node_modules/semver/semver.js:293:11)
    at SemVer (/usr/lib/node_modules/weex-toolkit/node_modules/semver/semver.js:286:12)
    at /usr/lib/node_modules/weex-toolkit/node_modules/check-node-version/index.js:113:33
    at module.exports (/usr/lib/node_modules/weex-toolkit/node_modules/map-values/index.js:9:18)
    at /usr/lib/node_modules/weex-toolkit/node_modules/check-node-version/index.js:106:20
    at end (/usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:16:15)
    at done (/usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:20:10)
    at each (/usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:26:7)
    at /usr/lib/node_modules/weex-toolkit/node_modules/run-parallel/index.js:36:43
    at /usr/lib/node_modules/weex-toolkit/node_modules/check-node-version/index.js:53:14

```

I did what you suggest before check weex version but I am still getting this semver error :(

**Comment by erha19** [comment]
I see that is a bug on `check-node-version` module, I will try to fix it.

**Comment by erha19** [comment]
Hi~, @marquesm91 ，I found this problem is because `semver` encountered an unreasonable version 0.22 when dealing with numbers, the version should be formatted like `x.x.x`,, your `npm` and `node` version is right, so maybe is a wrong version yarn you install on your platform, please check your `yarn` version and fix it.
Hope this helps you solve the problem，regards.

**Comment by erha19** [comment]
@marquesm91 If you have no other question, I will close this issue later.

**Comment by marquesm91** [comment]
@erha19 I am okay. You can close this issue. Thanks for your attention!
