### ISSUE TITLE
windows 10 下 weex debug 报错

### ISSUE THREAD

**Issue by turbidsoul** [apache/incubator-weex-cli#193]
This command need to install weex-devtool. Installing...
npm ERR! code EINTEGRITY
npm ERR! sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= integrity checksum failed when using sha1: wanted sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= but got sha1-uvHr2URpRPr4ioCO9ojX9KGOk+Y=. (1091691 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sccns\AppData\Roaming\npm-cache\_logs\2017-11-24T04_31_50_098Z-debug.log

Error: fatal error!
    at installer.(anonymous function).then (D:\nvm\v8.7.0\node_modules\weex-toolkit\node_modules\xtoolkit\src\Command.js:45:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

[2017-11-24T04_31_50_098Z-debug.log](https://github.com/weexteam/weex-toolkit/files/1500730/2017-11-24T04_31_50_098Z-debug.log)

**Comment by erha19** [comment]
Try to remove file install failed by delete `~/.xtoolkit/weex-devtool`, then try `weex update weex-devtool` again, make sure npm >= 5.

**Comment by wenjq0911** [comment]
@turbidsoul  I met same error.Did you fix the error?

**Comment by TimeStarRipple** [comment]
@erha19 I  met same error. And I try your solved method， but it's useless， there are some log
```
17711 warn tar ENOENT: no such file or directory, open 'C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\core-js-e7944677\library\fn\object\get-prototype-of.js'
17712 verbose unlock done using E:\Software\SoftwareData\nodejs\node_modules\npm\node_cache\_locks\staging-5986a8ba087ea96c.lock for C:\Users\zyb-xd\.xtoolkit\node_modules\.staging
17713 warn enoent ENOENT: no such file or directory, open 'C:\Users\zyb-xd\.xtoolkit\package.json'
17714 verbose enoent This is related to npm not being able to find a file.
17715 warn .xtoolkit No description
17716 warn .xtoolkit No repository field.
17717 warn .xtoolkit No README data
17718 warn .xtoolkit No license field.
17719 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-builder\node_modules\fsevents):
17720 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\fsevents-eeb8668a'
17721 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
17721 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
17722 verbose stack Error: sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= integrity checksum failed when using sha1: wanted sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= but got sha1-4k/2rIW3Ycrv8d7sH1Hjkve1LFM=. (712676 bytes)
17722 verbose stack     at Transform.on (E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\npm\node_modules\ssri\index.js:275:19)
17722 verbose stack     at emitNone (events.js:91:20)
17722 verbose stack     at Transform.emit (events.js:185:7)
17722 verbose stack     at endReadableNT (_stream_readable.js:974:12)
17722 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
17722 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
17723 verbose cwd C:\Users\zyb-xd\.xtoolkit
17724 verbose Windows_NT 6.1.7601
17725 verbose argv "D:\\work\\nodejs\\node.exe" "E:\\Software\\SoftwareData\\nodejs\\node_modules\\npm\\node_global_modules\\node_modules\\npm\\bin\\npm-cli.js" "install" "weex-devtool" "--loglevel=error"
17726 verbose node v6.9.2
17727 verbose npm  v5.5.1
17728 error code EINTEGRITY
17729 error sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= integrity checksum failed when using sha1: wanted sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= but got sha1-4k/2rIW3Ycrv8d7sH1Hjkve1LFM=. (712676 bytes)
17730 verbose exit [ 1, true ]
```

**Comment by turbidsoul** [comment]
@erha19 查不多就是按照你的方法解决的。

删除了 `c:\Users\<username>\.xtoolkit` 目录

设置了一个PYTHON的环境变量
`setx PYTHON x:\path\python.exe`

**Comment by wenjq0911** [comment]
@turbidsoul  
Deleting  `c:\Users\<username>\.xtoolkit`  and `setx PYTHON x:\path\python.exe `  solved the issue for me

**Comment by TimeStarRipple** [comment]
@turbidsoul 需要安装python才可以吗？

**Comment by erha19** [comment]
If you are installing on a windows platform, I suggest you add the `--no-optional` flag like `npm i weex-toolkit -g --no-optional` to skip the installation of some options and be sure not to use`npm` below version 5 for installation. If you have previously used an older version of `npm`,   You can try to upgrade`npm` and then reinstall.

For gyp library, python is needed.

**Comment by turbidsoul** [comment]
@TimeStarRipple 在安装的时候需要用到py27

我默认的是py3.6安装的时候报错，它的错误提示中，要求设置环境变量PYTHON=py27的python.exe

应该是node-gyp需要用到

**Comment by TimeStarRipple** [comment]
@erha19 My system is win7. And I use the `npm i weex-toolkit -g --no-optional` to install weex-toolkit. I also installed python and runed `setx PYTHON D:\work\Python27\python.exe`. But it's useless. 
Is it a problem of my system?
There are some log.
```
17717 warn tar ENOENT: no such file or directory, open 'C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\fsevents-dbe30a6a\node_modules\fstream\examples\symlink-write.js'
17718 warn tar ENOENT: no such file or directory, lstat 'C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\fsevents-dbe30a6a\node_modules'
17719 silly pacote core-js@http://registry.npm.taobao.org/core-js/download/core-js-2.5.1.tgz extracted to C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\core-js-e7944677 by content address 61464ms
17720 verbose unlock done using E:\Software\SoftwareData\nodejs\node_modules\npm\node_cache\_locks\staging-5986a8ba087ea96c.lock for C:\Users\zyb-xd\.xtoolkit\node_modules\.staging
17721 warn enoent ENOENT: no such file or directory, open 'C:\Users\zyb-xd\.xtoolkit\package.json'
17722 verbose enoent This is related to npm not being able to find a file.
17723 warn .xtoolkit No description
17724 warn .xtoolkit No repository field.
17725 warn .xtoolkit No README data
17726 warn .xtoolkit No license field.
17727 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-builder\node_modules\fsevents):
17728 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\fsevents-eeb8668a'
17729 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
17729 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
17730 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
17731 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\zyb-xd\.xtoolkit\node_modules\.staging\fsevents-dbe30a6a'
17732 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
17732 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
17733 verbose stack Error: sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= integrity checksum failed when using sha1: wanted sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= but got sha1-VoMvmSpkIHvSR3XnkEA/crFJL0o=. (644401 bytes)
17733 verbose stack     at Transform.on (E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\npm\node_modules\ssri\index.js:275:19)
17733 verbose stack     at emitNone (events.js:111:20)
17733 verbose stack     at Transform.emit (events.js:208:7)
17733 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
17733 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
17733 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
17734 verbose cwd C:\Users\zyb-xd\.xtoolkit
17735 verbose Windows_NT 6.1.7601
17736 verbose argv "D:\\work\\nodejs\\node.exe" "E:\\Software\\SoftwareData\\nodejs\\node_modules\\npm\\node_global_modules\\node_modules\\npm\\bin\\npm-cli.js" "install" "weex-devtool" "--loglevel=error"
17737 verbose node v8.9.0
17738 verbose npm  v5.5.1
17739 error code EINTEGRITY
17740 error sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= integrity checksum failed when using sha1: wanted sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= but got sha1-VoMvmSpkIHvSR3XnkEA/crFJL0o=. (644401 bytes)
17741 verbose exit [ 1, true ]
```

**Comment by erha19** [comment]
@TimeStarRipple This error looks like you lost some installation files during the installation process, I suggest you to using a mirror of `npmjs.org` like `npm.taobao.org`. Try this:
```
$ npm i nrm -g --registry=https://registry.npm.taobao.org
$ nrm use taobao
$ npm i weex-toolkit -g --no-optional
// or just
$ npm i weex-toolkit -g --no-optional --registry=https://registry.npm.taobao.org
```
Hope it will be work, thanks.

**Comment by TimeStarRipple** [comment]
@erha19 I used your method. But now I can't install weex-toolkit. I already used root permission.
There are some logs
```
8891 silly postinstall weex-toolkit@1.1.0-beta.7
8892 info lifecycle weex-toolkit@1.1.0-beta.7~postinstall: weex-toolkit@1.1.0-beta.7
8893 silly postinstall babel-cli@6.26.0
8894 info lifecycle babel-cli@6.26.0~postinstall: babel-cli@6.26.0
8895 verbose unlock done using E:\Software\SoftwareData\nodejs\node_modules\npm\node_cache\_locks\staging-42bf8becb508ee27.lock for E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\.staging
8896 verbose stack Error: EPERM: operation not permitted, scandir 'E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents\node_modules\getpass\node_modules'
8897 verbose cwd D:\
8898 verbose Windows_NT 6.1.7601
8899 verbose argv "D:\\work\\nodejs\\node.exe" "E:\\Software\\SoftwareData\\nodejs\\node_modules\\npm\\node_global_modules\\node_modules\\npm\\bin\\npm-cli.js" "i" "weex-toolkit" "-g" "--no-optional"
8900 verbose node v8.9.0
8901 verbose npm  v5.5.1
8902 error path E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents\node_modules\getpass\node_modules
8903 error code EPERM
8904 error errno -4048
8905 error syscall scandir
8906 error Error: EPERM: operation not permitted, scandir 'E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents\node_modules\getpass\node_modules'
8906 error  { Error: EPERM: operation not permitted, scandir 'E:\Software\SoftwareData\nodejs\node_modules\npm\node_global_modules\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents\node_modules\getpass\node_modules'
8906 error   stack: 'Error: EPERM: operation not permitted, scandir \'E:\\Software\\SoftwareData\\nodejs\\node_modules\\npm\\node_global_modules\\node_modules\\weex-toolkit\\node_modules\\weex-previewer\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
8906 error   errno: -4048,
8906 error   code: 'EPERM',
8906 error   syscall: 'scandir',
8906 error   path: 'E:\\Software\\SoftwareData\\nodejs\\node_modules\\npm\\node_global_modules\\node_modules\\weex-toolkit\\node_modules\\weex-previewer\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
8907 error Please try running this command again as root/Administrator.
8908 verbose exit [ -4048, true ]

```

**Comment by erha19** [comment]
@TimeStarRipple Try to delete all `weex-toolkit`'s dependences, running `npm i weex-toolkit -g` again as root/Administrator.
