### ISSUE TITLE
error of installing weex-devtool

### ISSUE THREAD

**Issue by tong3jie** [apache/incubator-weex-cli#208]
This command need to install weex-devtool. Installing...
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\juju\AppData\Roaming\npm-cache\_logs\2017-12-21T02_48_44_422Z-debug.log
Error: fatal error!
    at installer.(anonymous function).then (C:\Users\juju\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_xtoolkit@0.2.10@xtoolkit\src\Command.js:45:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

npm version: 5.6.0
node version: 8.9.0

**Comment by erha19** [comment]
See #142
