### ISSUE TITLE
import json error

### ISSUE THREAD

**Issue by phaibin** [apache/incubator-weex-cli#209]
try to import json in .vue file
`import variables from './assets/variables.json';`

and error occurs when preview using `weex src/change-password.js`

`
ERR! [webpack errors]
./src/assets/variables.json
Module parse failed: /Users/leon/Desktop/Workspace/GongPinHui/weex-mall/src/assets/variables.json Unexpected token (2:14)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:14)
    at Parser.pp$4.raise (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/leon/n/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/acorn/dist/acorn.js:3098:39)
 @ /Users/leon/n/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/weex-vue-loader/lib/script-loader.js!/Users/leon/n/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/babel-loader/lib!/Users/leon/n/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/change-password.vue 11:17-51
`

I've installed `json-loader`. And webpack 2.x no need to config json loader.

`npm run build` complete with no errors.

What else should I do?

**Comment by erha19** [comment]
@phaibin Under the common principle, weex toolkit does not include all the loaders in the tools. The next version of the tool will support configure the tool's compile options and configure it by file  `weex.build.config.js` on your project root.
As a temporary solution,You can use the `import variables from '. / Assets / variables.js'` instead of the` import variables from'. / Assets / variables.json'` to import your files content.

**Comment by phaibin** [comment]
Thanks for reply. "variables.json" shares settings with Stylus. I can't change it for now. 
Looking forward to your improvement.

**Comment by erha19** [comment]
@phaibin now it can be config on your own template, please check it.
