### ISSUE TITLE
1.预览整个项目，运行：weex src --entry src/foo.vue，为什么会报错？2.debug模式开始，扫第一个二维码能够显示设备信息，扫码自己的工程就一直是加载中，为什么？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#224]
问题1：
E:\wxnew>weex src --entry src/foo.vue
C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\TemplatedPathPlugin.js:48
                        if(!allowEmpty) throw new Error(`Path variable ${match} not implemented in this context: ${input}`);
                                        ^

Error: Path variable [name] not implemented in this context: C:\Users\myth\.weex_tmp\[name].weex.js
    at C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\TemplatedPathPlugin.js:48:26
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at MainTemplate.replacePathVariables (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\TemplatedPathPlugin.js:71:4)
    at MainTemplate.applyPluginsWaterfall (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:92:24)
    at Compilation.getPath (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\Compilation.js:1424:28)
    at applyPluginsAsync.err (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\Compiler.js:356:29)
    at Compiler.applyPluginsAsyncSeries (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:195:46)
    at Compiler.emitAssets (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\Compiler.js:354:8)
    at onCompiled (C:\Users\myth\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_webpack@3.10.0@webpack\lib\Compiler.js:240:9)

问题2：

![20180116094153](https://user-images.githubusercontent.com/31499235/34968073-ea30fe56-faa1-11e7-95b4-1be16780152c.jpg)

**Comment by erha19** [comment]
@AugTangLooks like you did not install `weex-toolkit` properly, can you run `weex -v` to show me your weex version? If not, try:
```
npm un weex-toolkit -g // Maybe you need to manually delete
npm i weex-toolkit@latest -g
```

**Comment by AugTang** [comment]
这个问题已经解决，现在问题是使用debug模式，手机扫地一个二维码能够连接设备，当扫我项目二维码(第二个)时，设备上一直是加载中，请问这是怎么回事？ @erha19

**Comment by erha19** [comment]
@AugTang Show me your code of your bundle, maybe there have some wrongs while compiling the source code.

**Comment by AugTang** [comment]
1.index.we
![image](https://user-images.githubusercontent.com/31499235/34930709-dd89af6e-fa05-11e7-89c8-ee69d1a288f1.png)
1,1、使用预览没问题。
我按照官网新建的项目，没有去改任何代码，后面吧.vue更改为.we也不可以。

**Comment by wyh497823256** [comment]
遇到一样的问题。
![image](https://user-images.githubusercontent.com/8830870/34969808-9fdda9d0-faab-11e7-8f5a-a6713ffbcdb7.png)
weex debug src -e src/index.vue 扫描主页的时候一直加载中...

**Comment by erha19** [comment]
@AugTang @wyh497823256  
I have been fixed this issue on `weex-previewer@1.4.0` and `weex-devtool@0.3.3`, that cause by a big change of webpack 3+ compile logic. you can upgrade it by:
```
weex update weex-previewer@1.4.0
weex update weex-devtool@0.3.3
```

**Comment by wyh497823256** [comment]
@erha19 谢谢
如果单独升级 
`weex update weex-previewer@1.4.0`
运行  weex src/index.vue 
会报错
`module.js:557
    throw err;
    ^
Error: Cannot find module 'webpack-sources'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/lib/DependenciesBlockVariable.js:7:23)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
`
所以要先升级以下命令：
` weex update weex-builder@0.3.8`

**Comment by liushuhui** [comment]
@erha19  大佬，我刚刚升到1.2.6版本，但是weex debug 报错，安装weex-debugger失败。能帮我看下吗？
![image](https://user-images.githubusercontent.com/26155477/35182229-920b7770-fe0b-11e7-8ac2-db92ae4b990d.png)
![image](https://user-images.githubusercontent.com/26155477/35182231-997cf10a-fe0b-11e7-95e3-2fa0700c7944.png)

**Comment by erha19** [comment]
@liushuhui you can't install chromium because of the wall, you can run `set PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org && weex debug` again, for mac, the `set` need to change as `export`.
see:https://github.com/GoogleChrome/puppeteer/issues/1597

**Comment by liushuhui** [comment]
@erha19  还是报这个错误。大佬

**Comment by erha19** [comment]
@liushuhui try this `npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org` and run `weex debug` in a new shell (the Environment Variables may not take effect immediately )

**Comment by liushuhui** [comment]
@erha19  大佬，又出现这个错误。。。。 
![image](https://user-images.githubusercontent.com/26155477/35192336-f31d7a30-feca-11e7-9184-dd84fe68301a.png)

**Comment by erha19** [comment]
update your weex-toolkit to 1.2.6

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/35193592-c8227aa0-fedf-11e7-852b-d911b7611a1a.png)
@erha19 安装最新的，又是这样了

**Comment by erha19** [comment]
@AugTang The `weex-toolkit` does not have permission to access your file system to create the necessary files like `config.json`, you can use the command line with administrator privileges or manually create this file.

**Comment by liushuhui** [comment]
@erha19  大佬，我按照您的方法：npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org，但结果出现这么一个错误，怎么解决呢，麻烦您了。
![image](https://user-images.githubusercontent.com/26155477/35204655-9d971508-ff6a-11e7-8e68-a135b2fb7f80.png)

**Comment by erha19** [comment]
@liushuhui you need to remove your `c:\Users\.......\node_modules\weex-debugger(look at your log)`, and run `weex debug` again.

**Comment by liushuhui** [comment]
@erha19 
这个是网络原因导致下载失败吗？

![image](https://user-images.githubusercontent.com/26155477/35215270-acf390d8-ff9e-11e7-92ab-6808ce7e7619.png)
