### ISSUE TITLE
Warning:The session with native was closed,please restart your native app!

### ISSUE THREAD

**Issue by wyh497823256** [apache/incubator-weex-cli#230]
![image](https://user-images.githubusercontent.com/8830870/35023233-c3aa289c-fb74-11e7-8dd9-9774b34779ff.png)

> 运行：weex debug src -e src/index.vue

> 命令 weex platform add android  

> 修改 weex SDK 0.17.0 

> 使用Android Studio 运行 刚刚添加的项目 android  得到一个 weex playground app

> 扫描 左下角 二维码，界面提示 debug server connected 
 

> 再扫描右下角二维码,出现如下提示

 `Warning:The session with native was closed,please restart your native app!`

> 同时界面上出现

 `render error:wx_create_instance_error`

> ps:相同的操作，在官网提供的 weex playground 工具当中，运行正常，能显示界面

请问这是原因？谢谢！

**Comment by wyh497823256** [comment]
你好，用了从官网下载的weex playground app 扫描我的项目，app出现闪退，并且抛出一下异常：
`FATAL EXCEPTION: pool-7-thread-1
                                                                Process: com.alibaba.weex, PID: 4534
                                                                java.lang.IllegalStateException: Must call preConnect
                                                                    at com.taobao.weex.urlconnection.WeexURLConnectionManagerImpl.throwIfNoConnection(WeexURLConnectionManagerImpl.java:128)
                                                                    at com.taobao.weex.urlconnection.WeexURLConnectionManagerImpl.httpExchangeFailed(WeexURLConnectionManagerImpl.java:99)
                                                                    at com.taobao.weex.urlconnection.WeexURLConnectionManager.httpExchangeFailed(WeexURLConnectionManager.java:115)
                                                                    at com.alibaba.weex.extend.adapter.InterceptWXHttpAdapter$1.httpExchangeFailed(InterceptWXHttpAdapter.java:76)
                                                                    at com.taobao.weex.adapter.DefaultWXHttpAdapter$1.run(DefaultWXHttpAdapter.java:95)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                    at java.lang.Thread.run(Thread.java:776)`

**Comment by erha19** [comment]
@wyh497823256  please upgrade to the latest version of `weex-toolkit`.

**Comment by wyh497823256** [comment]
@erha19  你好！

1. 我当前环境是否是最新版？
```
   v1.1.0-beta.7
 - weexpack : v1.0.8
 - weex-builder : v0.3.12
 - weex-devtool : v0.3.3
 - weex-previewer : v1.4.4
```
2.  另外 有一个关于 android sdk **0.17.0** 的bug，应该提交在哪（我实在找不到提交的地方），我先描述下问题：
使用 weex 内置组件**navigator** 跳转
```
navigator.push({
                        url: 'http://192.168.0.107:8083/dist/coupon/index.js',
                        animated: "true"
                    }, event => {

                    })
```
**出现第二个界面获取当前时间和实际时间相差8个小时**
但是第一个界面通过扫描二维码预览的界面，时间获取正常

**Comment by erha19** [comment]
@wyh497823256 
1. latest version is `1.2.7`, you can run `npm i weex-toolkit@latest -g` to install the latest verison.
2. you can report your issue on the mailing list of `apache weex` , see https://github.com/apache/incubator-weex/blob/master/CONTRIBUTING.md

**Comment by wyh497823256** [comment]
@erha19 OK! Thank you!

**Comment by wyh497823256** [comment]
你好 ！ @erha19  版本已经升级，但是在自己运行的weex playground app（android sdk 0.17.0 ）上，调试依然出现`render error:wx_create_instance_error`

- 环境：

```
   v1.2.7
 - weex-debugger : v1.0.0
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
```

- 操作步骤如下：

> weex debug src/ -e src/index.vue 

> 使用运行的weex playground app 扫描二维码
![image](https://user-images.githubusercontent.com/8830870/35367270-75f449da-01b8-11e8-895a-51aa2043e4e6.png)
**未开启JS Debug 开关的情况下，界面可以显示**
![image](https://user-images.githubusercontent.com/8830870/35367285-87fd9dfc-01b8-11e8-9789-f3b46da4d2e2.png)

> 开启JS Debug
![image](https://user-images.githubusercontent.com/8830870/35367435-3970dd2e-01b9-11e8-97cc-f168101b8ac7.png)
![image](https://user-images.githubusercontent.com/8830870/35367446-41f3086e-01b9-11e8-9b4c-59d395f34b5b.png)

- Android Stduio logcat 获取到以下异常信息：

```
01-25 10:08:13.263 32259-32278/com.weex.app E/weex: [WXBridgeManager] invokeInitFramework java.lang.AbstractMethodError: abstract method "int com.taobao.weex.common.IWXBridge.initFrameworkEnv(java.lang.String, com.taobao.weex.bridge.WXParams, java.lang.String, boolean)"
                                                        at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1597)
                                                        at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:1410)
                                                        at com.taobao.weex.bridge.WXBridgeManager.access$300(WXBridgeManager.java:107)
                                                        at com.taobao.weex.bridge.WXBridgeManager$6.run(WXBridgeManager.java:1394)
                                                        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49)
                                                        at android.os.Handler.handleCallback(Handler.java:761)
                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                        at android.os.Looper.loop(Looper.java:156)
                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
01-25 10:08:13.264 32259-32278/com.weex.app E/weex: [WXBridgeManager] invokeCreateInstance: framework.js uninitialized.
```

**Comment by wyh497823256** [comment]
@erha19 已经找到问题了 。
由于 0.17.0 移除了方法 `WXSDKEngine.switchDebugModel(true, debug_url);`
要修改成：
```
 WXEnvironment.sRemoteDebugMode =true;
        WXEnvironment.sRemoteDebugProxyUrl = debug_url;
```
这样就能解决问题！
