### ISSUE TITLE
weex update weexpack ERR

### ISSUE THREAD

**Issue by Aibric** [apache/incubator-weex-cli#238]
```
$ weex update weexpack
? update package "weexpack" now? Yes
npm ERR! code EINTEGRITY
npm ERR! sha1-wVm41b4PnlpvNG2rlPFs4CIWG4g= integrity checksum failed when using sha1: wanted sha1-wVm41b4PnlpvNG2rlPFs4CIWG4g= but got sha1-tDLdM1i2NM914eRmQ2gkBTPB3b4=. (2443 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-01-19T08_29_47_026Z-debug.log

```

```
3289 silly pacote fs-extra@0.26.7 extracted to C:\Users\Administrator\.xtoolkit\node_modules\.staging\fs-extra-23fb6fc6 by content address 1674ms
3290 verbose stack Error: sha1-wVm41b4PnlpvNG2rlPFs4CIWG4g= integrity checksum failed when using sha1: wanted sha1-wVm41b4PnlpvNG2rlPFs4CIWG4g= but got sha1-tDLdM1i2NM914eRmQ2gkBTPB3b4=. (2443 bytes)
3290 verbose stack     at Transform.on (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:275:19)
3290 verbose stack     at emitNone (events.js:110:20)
3290 verbose stack     at Transform.emit (events.js:207:7)
3290 verbose stack     at endReadableNT (_stream_readable.js:1047:12)
3290 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
3290 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
3291 verbose cwd C:\Users\Administrator\.xtoolkit
3292 verbose Windows_NT 10.0.14393
3293 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "weexpack" "--loglevel=error" "--registry=http://registry.npmjs.org"
3294 verbose node v8.1.2
3295 verbose npm  v5.6.0
3296 error code EINTEGRITY
3297 error sha1-wVm41b4PnlpvNG2rlPFs4CIWG4g= integrity checksum failed when using sha1: wanted sha1-wVm41b4PnlpvNG2rlPFs4CIWG4g= but got sha1-tDLdM1i2NM914eRmQ2gkBTPB3b4=. (2443 bytes)
3298 verbose exit [ 1, true ]
```

**Comment by erha19** [comment]
@Aibric Try to remove `C:\Users\Administrator\.xtoolkit\node_modules\weex-pack` and try `weex update weexpack@1.0.1` again.

**Comment by Aibric** [comment]
@erha19  已解决，谢谢！
