### ISSUE TITLE
升级版本1.2.6之后，出现两个问题：1.运行调试预览无效：weex src --entry src/index.vue？2.运行weex debug，安装失败？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#240]
1.预览无效，没任何提示：

![yul](https://user-images.githubusercontent.com/31499235/35155504-c18a22e2-fd68-11e7-9f35-be7a4c236f90.png)

2.运行debug，安装失败：

![debug](https://user-images.githubusercontent.com/31499235/35155478-aadf961c-fd68-11e7-85ce-4d0c16da01b9.png)

@erha19

**Comment by erha19** [comment]
preview command is change to weex preview xxx.vue

**Comment by AugTang** [comment]
那个debug报错呢
@erha19

**Comment by Aibric** [comment]
我运行 `weex debug` 同样有错误 @erha19 
```
$ weex debug
This command need to install weex-debugger. Installing...
ERROR: Failed to download Chromium r515411! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1016:11)
    at TLSWrap.onread (net.js:609:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.13.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-01-20T01_37_35_837Z-debug.log
9:37:36 : Error: fatal error!
```


```
45218 verbose stack Error: puppeteer@0.13.0 install: `node install.js`
45218 verbose stack Exit status 1
45218 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
45218 verbose stack     at emitTwo (events.js:125:13)
45218 verbose stack     at EventEmitter.emit (events.js:213:7)
45218 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
45218 verbose stack     at emitTwo (events.js:125:13)
45218 verbose stack     at ChildProcess.emit (events.js:213:7)
45218 verbose stack     at maybeClose (internal/child_process.js:897:16)
45218 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
45219 verbose pkgid puppeteer@0.13.0
45220 verbose cwd C:\Users\Administrator\.xtoolkit
45221 verbose Windows_NT 10.0.14393
45222 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "weex-debugger" "--loglevel=error" "--registry=http://registry.npmjs.org"
45223 verbose node v8.1.2
45224 verbose npm  v5.6.0
45225 error code ELIFECYCLE
45226 error errno 1
45227 error puppeteer@0.13.0 install: `node install.js`
45227 error Exit status 1
45228 error Failed at the puppeteer@0.13.0 install script.
45228 error This is probably not a problem with npm. There is likely additional logging output above.
45229 verbose exit [ 1, true ]

```

**Comment by liushuhui** [comment]
@erha19  我也是这个错误 
![image](https://user-images.githubusercontent.com/26155477/35182536-e5bfc596-fe11-11e7-94b4-a769fc4a0244.png)

**Comment by erha19** [comment]
@liushuhui run `weex config registry https://registry.npm.taobao.org/`, then run `weex debug` again.

**Comment by erha19** [comment]
@AugTang remove `c:\user\xxx\.xtoolkit\node_modules\weex-debugger` then run it again.

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/35182640-c092398c-fe13-11e7-93e1-6d87fac469d6.png)
@erha19 没有这个文件

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/35182790-35582e78-fe16-11e7-912b-4b3855583fd2.png)

**Comment by liushuhui** [comment]
@erha19 还是这个错误

**Comment by AugTang** [comment]
@erha19 没有那个文件

**Comment by AugTang** [comment]
@erha19 没有那个文件

**Comment by zhangzhenfei** [comment]
I have encountered the same problem. Have you solved it now?

**Comment by orangeskiller** [comment]
run `npm config set puppeteer_download_host=https://npm.taobao.org/mirrors`, then run `weex debug`.
@liushuhui @zhangzhenfei @AugTang
