### ISSUE TITLE
TypeError: Object #<Object> has no method 'homedir'

### ISSUE THREAD

**Issue by dedecom** [apache/incubator-weex-cli#257]
![image](https://user-images.githubusercontent.com/26832186/35319900-c69ea886-011c-11e8-8fc6-a95ea5eccf00.png)

const home = os.homedir();
                ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roamin
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by erha19** [comment]
@dedecom You can try update `weex-previewer` to the latest version of `weex update weex-previewer`.
