### ISSUE TITLE
weex  create 命令报错：Cannot find module '../src/create

### ISSUE THREAD

**Issue by aa453509345** [apache/incubator-weex-cli#259]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)
  weex -v
   v1.2.7
 - weexpack : v1.0.0
 - weex-debugger : v1.0.0
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4

Mac平台
## The key error stack message.
module.js:472
    throw err;
    ^

Error: Cannot find module '../src/create'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Carry/.xtoolkit/node_modules/weexpack/bin/weexpack-create.js:9:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by erha19** [comment]
@aa453509345 upgrade your `weexpack` by `weex update weexpack@latest`.

**Comment by erha19** [comment]
@aa453509345 If you have no other questions, I will close this issue:)
