### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by esmeetu** [apache/incubator-weex-cli#27]
运行`weex index.we --qr` 或者`weex index.we`

info 0.5.8

用Playground扫二维码后(弹出浏览器页面后)报错：

fs.js:1431
    throw error;
    ^

Error: watch vue-hackernews/node_modules/acorn ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at watch (/usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:221:8)
    at /usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:230:9
    at /usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:38:18
    at FSReqWrap.oncomplete (fs.js:123:15)

PS：`index.we`在我的`home`下

**Comment by lvscar** [comment]
请问你使用的是什么操作系统？
建议检查一下文件和目录的权限.    特别是检查下这个目录有没有接入到某种云存储(iCloud)同步目录列表里。

**Comment by esmeetu** [comment]
`4.8.2-1-ARCH`
之前clone到home下的vue-hackernews，没有其他同步了。
又运行一次，手机白屏。

fs.js:1431
    throw error;
    ^

Error: watch vue-hackernews/node_modules/babel-code-frame ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at watch (/usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:221:8)
    at /usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:230:9
    at /usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /usr/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:38:18
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by esmeetu** [comment]
就感觉weex先依次读取当前文件夹下的`node_modules`，没有就挨个文件夹搜索它。不知道是不是个例。

**Comment by Jinjiang** [comment]
现在这个问题还存在吗？另外我看你错误信息里的仓库名是 vue-hackernews 所以也想确定一下你运行的代码是怎样的，如果源代码是来自 vuejs/vue-hackernews 仓库，应该是不能直接运行的，可以在 Weex 上运行的 hackernews 版本在 https://github.com/weexteam/weex-hackernews
谢谢
