### ISSUE TITLE
weex run ios error 

### ISSUE THREAD

**Issue by javaKhan** [apache/incubator-weex-cli#290]
## Your development environment
- weex-toolkit verison (Run `weex -v`)
```
localhost:~ kevin$ weex -v
   v1.1.0-beta.7
 - weexpack : v1.0.18
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.3
 - weex-previewer : v1.4.4
```
- platform (Win/Mac/Ubuntu..)
macOs 10.13.3 high sierra

## The key error stack message.
after phone device selected,display  No such file or directory
```
? Choose one of the following devices iPhone ios: 11.2.5
2018-02-13 10:00:47.225 xcodebuild[76693:4708837]  DTDeviceKit: deviceType from d4e4db388d8ad81ebc51a3e28e81443d873ef664 was NULL
10:00:47 : building...
/bin/sh: /Users/kevin/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory
10:00:47 : Success!
10:00:47 : Error:Error: Command failed: /Users/kevin/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build . Debug
/bin/sh: /Users/kevin/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at _runAppOnDevice (/Users/kevin/.xtoolkit/node_modules/weexpack/lib/run/ios.js:498:20)
    at /Users/kevin/.xtoolkit/node_modules/weexpack/lib/run/ios.js:375:7
    at runApp (/Users/kevin/.xtoolkit/node_modules/weexpack/lib/run/ios.js:371:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by erha19** [comment]
@javaKhan do you have the env of [cocopod](https://cocoapods.org/)?

**Comment by Martin-Mo** [comment]
Same problem here. It works when running on simulator.

**Comment by erha19** [comment]
@javaKhan @Martin-Mo see https://github.com/weexteam/weex-toolkit/issues/300#issuecomment-370652227.
