### ISSUE TITLE
[ERROR] weex create: ReferenceError: cfg is not defined at weexpack/lib/create/index.js:39:43

### ISSUE THREAD

**Issue by void-ecs** [apache/incubator-weex-cli#293]
## Development environment
```
❯ weex -v
   v1.2.9
 - weexpack : v1.1.0
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

❯ node -v
v8.9.1

❯ npm -v
5.6.0

❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C205
```

## Error Stack
```
ReferenceError: cfg is not defined
    at module.exports (/Users/skyisland/.xtoolkit/node_modules/weexpack/lib/create/index.js:39:43)
    at Object.<anonymous> (/Users/skyisland/.xtoolkit/node_modules/weexpack/bin/weexpack-create.js:98:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Command.immediateStart (/Users/skyisland/.nvm/versions/node/v8.9.1/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/Command.js:101:5)
    at Command._invoke (/Users/skyisland/.nvm/versions/node/v8.9.1/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/Command.js:79:14)
    at Command.run (/Users/skyisland/.nvm/versions/node/v8.9.1/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/Command.js:53:12)
    at XToolkit._runCmd (/Users/skyisland/.nvm/versions/node/v8.9.1/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/xtoolkit.js:122:27)
    at XToolkit._done (/Users/skyisland/.nvm/versions/node/v8.9.1/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/xtoolkit.js:139:12)
    at process.nextTick (/Users/skyisland/.nvm/versions/node/v8.9.1/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/xtoolkit.js:77:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

## Steps to reproduce the problem
Run the following command:
```
weex create test
```

**Comment by erha19** [comment]
@void-ecs please upgrade your weexpack  with `weex update weexpack`, it have been fixed on version `v1.1.1`. changelog here https://github.com/weexteam/weex-pack/blob/master/CHANGELOG.en.md.
