### ISSUE TITLE
nom run ios报错

### ISSUE THREAD

**Issue by codeliu6572** [apache/incubator-weex-cli#300]
h.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe9cfb1ceb0>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
        ProcessProductPackaging "" build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/WeexDemo.app.xcent
(1 failure)
2018-02-27 00:05:13.874 xcodebuild[2271:63119] couldn't read dependency graph from '/Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph': Permission denied
2018-02-27 00:05:13.874 xcodebuild[2271:63119] unable to create temporary file at /Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph-2e3Xr6gG: Permission denied
2018-02-27 00:05:13.875 xcodebuild[2271:63119]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe9cfb1ceb0>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
00:05:13 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -schemeWeexDemo -configuration Debug -destination id=E6ACC17B-74BE-4B13-A341-916AE58EB49B -sdk iphonesimulator -derivedDataPath build clean build
2018-02-27 00:04:54.545 xcodebuild[2271:63076] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ZLXCodeLine.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-27 00:04:54.546 xcodebuild[2271:63076] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-27 00:04:54.546 xcodebuild[2271:63076] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-27 00:04:54.546 xcodebuild[2271:63076] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-27 00:04:54.547 xcodebuild[2271:63076] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ActivatePowerMode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-27 00:04:55.719 xcodebuild[2271:63119] couldn't read dependency graph from '/Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph': Permission denied
2018-02-27 00:04:55.719 xcodebuild[2271:63119] unable to create temporary file at /Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph-jbh6JtKC: Permission denied
2018-02-27 00:04:55.720 xcodebuild[2271:63119]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe9cfb1ceb0>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** CLEAN FAILED **

The following build commands failed:
        Clean.Remove clean build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build
(1 failure)
2018-02-27 00:04:56.187 xcodebuild[2271:63119] couldn't read dependency graph from '/Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph': Permission denied
2018-02-27 00:04:56.187 xcodebuild[2271:63119] unable to create temporary file at /Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph-SC21dVY7: Permission denied
2018-02-27 00:04:56.187 xcodebuild[2271:63119]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe9cfb1ceb0>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-02-27 00:04:56.361 xcodebuild[2271:63119] couldn't read dependency graph from '/Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph': Permission denied
2018-02-27 00:04:56.361 xcodebuild[2271:63119] unable to create temporary file at /Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph-m9I1OA9S: Permission denied
2018-02-27 00:04:56.361 xcodebuild[2271:63119]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe9cfb1ceb0>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
        ProcessProductPackaging "" build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/WeexDemo.app.xcent
(1 failure)
2018-02-27 00:05:13.874 xcodebuild[2271:63119] couldn't read dependency graph from '/Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph': Permission denied
2018-02-27 00:05:13.874 xcodebuild[2271:63119] unable to create temporary file at /Users/Codeliu/Desktop/WeexTest/listlist/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/dgph-2e3Xr6gG: Permission denied
2018-02-27 00:05:13.875 xcodebuild[2271:63119]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe9cfb1ceb0>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at _buildOnSimulator (/Users/Codeliu/.xtoolkit/node_modules/weexpack/lib/run/ios.js:328:18)
    at /Users/Codeliu/.xtoolkit/node_modules/weexpack/lib/run/ios.js:300:7
    at new Promise (<anonymous>)
    at buildApp (/Users/Codeliu/.xtoolkit/node_modules/weexpack/lib/run/ios.js:289:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by erha19** [comment]
@codeliu6572 do you have the env of `cocopod`?

**Comment by codeliu6572** [comment]
yes, i am sure

**Comment by erha19** [comment]
@codeliu6572 you may not have the permission to read dependency graph and I need more information about your error.

**Comment by codeliu6572** [comment]
@erha19 
bogon:tabbarpro Codeliu$ sudo weex platform add ios
Password:

   ┌──────────────────────────────────────────────┐
   │                                              │
   │                                              │
   │   Update available 1.1.1 → 1.1.5             │
   │   Run weex update weexpack@1.1.5 to update   │
   │                                              │
   │                                              │
   └──────────────────────────────────────────────┘

19:16:56 : Adding ios weexpack-ios@4.1.5 ...
19:16:56 : Success!
bogon:tabbarpro Codeliu$ sudo weex run ios

   ┌──────────────────────────────────────────────┐
   │                                              │
   │                                              │
   │   Update available 1.1.1 → 1.1.5             │
   │   Run weex update weexpack@1.1.5 to update   │
   │                                              │
   │                                              │
   └──────────────────────────────────────────────┘

19:17:04 : npm run build

> tabbarpro@1.0.0 build /Users/Codeliu/Desktop/weex练习/简易项目/tabbarpro
> webpack --env.NODE_ENV=common

Hash: 8386ed961d46f7e1665eab708bb87ce2c50a1e60
Version: webpack 3.11.0
Child
    Hash: 8386ed961d46f7e1665e
    Time: 7005ms
                         Asset     Size  Chunks                    Chunk Names
                  index.web.js   620 kB       0  [emitted]  [big]  index
     components/setting.web.js   620 kB       1  [emitted]  [big]  components/setting
    components/mycenter.web.js   620 kB       2  [emitted]  [big]  components/mycenter
        components/list.web.js   620 kB       3  [emitted]  [big]  components/list
        components/home.web.js   620 kB       4  [emitted]  [big]  components/home
     components/aboutus.web.js   620 kB       5  [emitted]  [big]  components/aboutus
                 vendor.web.js  13.5 kB       6  [emitted]         vendor
       [0] (webpack)/buildin/global.js 509 bytes {0} {1} {2} {3} {4} {5} [built]
      [40] ./.temp/index.js 448 bytes {0} [built]
      [41] ./src/index.vue 1.76 kB {0} [built]
      [42] ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-12abeac9","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 1.55 kB {0} [built]
      [43] ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-12abeac9","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 187 bytes {0} [built]
      [44] ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 120 bytes {0} [built]
      [45] ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-12abeac9","hasScoped":false}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 333 bytes {0} [built]
      [46] multi ./node_modules/phantom-limb/index.js 28 bytes {6} [built]
        + 40 hidden modules
Child
    Hash: ab708bb87ce2c50a1e60
    Time: 2560ms
                     Asset     Size  Chunks             Chunk Names
                  index.js  4.42 kB       0  [emitted]  index
     components/setting.js  4.43 kB       1  [emitted]  components/setting
    components/mycenter.js  4.43 kB       2  [emitted]  components/mycenter
        components/list.js  4.49 kB       3  [emitted]  components/list
        components/home.js  4.45 kB       4  [emitted]  components/home
     components/aboutus.js  4.41 kB       5  [emitted]  components/aboutus
      [20] ./src/index.vue?entry=true 1.83 kB {0} [built]
      [21] ./node_modules/weex-vue-loader/lib/style-loader.js!./node_modules/weex-vue-loader/lib/style-rewriter.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 19 bytes {0} [built]
      [22] ./node_modules/weex-vue-loader/lib/script-loader.js!./node_modules/babel-loader/lib!./node_modules/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 120 bytes {0} [built]
      [23] ./node_modules/weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 183 bytes {0} [built]
        + 20 hidden modules
19:17:12 : Move JSbundle to dist
19:17:12 : start iOS app
============Build Config============
AppName      : WeexApp
Version      : 0.1
BuildVersion : 0.1.0
AppId        : com.alibaba.weex
WeexBundle   : index.js
Ws           : ws://192.168.1.141:8080
CodeSign     :
Profile      :
19:17:12 : If you want to change build config.please modify ios.config.json
19:17:12 : pod update
19:17:12 : Hot Reload socket: ws://192.168.1.141:8080
? Choose one of the following devices (Use arrow keys)
? Choose one of the following devices iPhone 8 ios: 11.2
19:17:23 : Buiding project...
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/
WeexDemo.build/Script-CD3187D7C603AFBFADBBAE7F.sh
(1 failure)
19:17:24 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=15CCC22B-5292-4708-B32B-BA5FB842CFFC -sdk iphonesimulator -derivedDataPath build clean build
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Script-CD3187D7C603AFBFADBBAE7F.sh
(1 failure)

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at _buildOnSimulator (/Users/Codeliu/.xtoolkit/node_modules/weexpack/lib/run/ios.js:328:18)
    at /Users/Codeliu/.xtoolkit/node_modules/weexpack/lib/run/ios.js:300:7
    at new Promise (<anonymous>)
    at buildApp (/Users/Codeliu/.xtoolkit/node_modules/weexpack/lib/run/ios.js:289:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
that is all

**Comment by erha19** [comment]
@codeliu6572 open `WeexDemo.xcodeproj` on your Xcode and select the project `Build Phases`, remove all `[CP]` start config of your project, then run it again., also you need to upgrade your `pod` probably.

**Comment by codeliu6572** [comment]
@erha19 I can run project by myself before, but can't run by weex.Thank you for your answer, i can run project by weex now.
