### ISSUE TITLE
npm ERR! write after end

### ISSUE THREAD

**Issue by hphua** [apache/incubator-weex-cli#310]
## development environment
```
C:\Users\Thinkpad>node -v
v8.9.4

C:\Users\Thinkpad>npm -v
5.7.1

C:\Users\Thinkpad>weex -v
   v1.2.9
 - weexpack : v1.1.5
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6
```

## run command
`weex debug`

## output 
```
C:\Users\Thinkpad>weex debug
This command need to install weex-debugger. Installing...
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting javascript-obfuscator@0.8.6:
npm ERR! sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= integrity checksum failed when using
sha1: wanted sha1-bOF6tNfiGWHAzursaPln+Nl1Ha0= but got sha512-WrGjMk1GPN8Q2UfbIOIrDM4EY2C5p0oTYljIzvnTIOl+msZNCY1NYdnAoqZ3HA8O1XeyjNpnu9/+6Q+bqRYMqg== sha1-5WbC7fopuHV8zgnlH8RR/ryZEZ0=. (780640 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thinkpad\AppData\Roaming\npm-cache\_logs\2018-03-01T15_19_07_905Z-debug.log
23:21:47 : Error: fatal error!
```
that log ==>
```
18395 silly pacote trying boxen@1.2.2 by hash: sha1-Px1AMsMP/qnUsCwyLq8up0HcvOU=
18396 silly pacote data for sha1-5MyPoPAJ+4KaquI4VaKTYL4fbBE= not present. Using manifest.
18397 silly pacote data for sha512-2KWLTLsfpi/oYPGNBEniPcFzr1GW/s+Xq/4hJmTQRdE8ULuRwGnRPuVhS/cf+Z4ZEXNo7EO2f6oydHJQd94KMg== not present. Using manifest.
18398 silly pacote data for sha512-GxMpax8a/VgcfRrVy0gXD6yLd5ePYbXX/5zGgTVYp4wXtJklS8Z2VaUArJgc//f6/Dzil7BaJObdSv8eKKCPgg== not present. Using manifest.
18399 silly pacote data for sha1-Px1AMsMP/qnUsCwyLq8up0HcvOU= not present. Using manifest.
18400 http fetch GET 200 https://registry.npm.taobao.org/node-watch 1038ms
18401 verbose stack Error: write after end
18401 verbose stack     at writeAfterEnd (_stream_writable.js:236:12)
18401 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
18401 verbose stack     at PassThrough.Writable.end (_stream_writable.js:553:10)
18401 verbose stack     at ReadEntry.entry.on (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\extract-stream.js:19:41)
18401 verbose stack     at emitOne (events.js:121:20)
18401 verbose stack     at ReadEntry.emit (events.js:211:7)
18401 verbose stack     at ReadEntry.emit (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:287:25)
18401 verbose stack     at ReadEntry.[maybeEmitEnd] (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:240:12)
18401 verbose stack     at ReadEntry.end (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:153:27)
18401 verbose stack     at Unpack.[consumeBody] (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:210:13)
18401 verbose stack     at Unpack.[consumeChunkSub] (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:391:40)
18401 verbose stack     at Unpack.[consumeChunk] (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:362:30)
18401 verbose stack     at Unzip.(anonymous function).on.chunk (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:291:59)
18401 verbose stack     at emitOne (events.js:116:13)
18401 verbose stack     at Unzip.emit (events.js:211:7)
18401 verbose stack     at Unzip.emit (C:\Users\Thinkpad\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:287:25)
18402 verbose cwd C:\Users\Thinkpad\.xtoolkit
18403 verbose Windows_NT 10.0.10586
18404 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Thinkpad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "weex-debugger" "--loglevel=error" "--registry=https://registry.npm.taobao.org/"
18405 verbose node v8.9.4
18406 verbose npm  v5.7.1
18407 error write after end
18408 verbose exit [ 1, true ]
```

**Comment by erha19** [comment]
@hphua I found the `npm@4` maybe a perfect choice for windows people, you can run `npm i npm@4 -g` and run `weex debug` again.

**Comment by hphua** [comment]
@erha19 Thank you。use npm@4 is Feasible method.

**Comment by anoop992** [comment]
sss
