### ISSUE TITLE
weex compile 添加-m选项后没有// { "framework": "Vue"} 

### ISSUE THREAD

**Issue by DinoDom** [apache/incubator-weex-cli#326]
```
npm -v
5.5.1
```
```
node -v
v9.2.0
```
- weex-toolkit verison
```
weex -v
   v1.2.9
 - weexpack : v1.1.5
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6
```

- platform `Mac`

## The key error stack message.
使用`weex compile src js -m`编译打包vue文件生成的js文件第一行没有
`// { "framework": "Vue"} `
使用`weex compile src js`是有的

**Comment by erha19** [comment]
@DinoDom you can upgrade your `weex-builder` by `weex update weex-builder@latest`.

**Comment by DinoDom** [comment]
@erha19 this is what i got from update `weex-builder`

```
$ weex update weex-builder@0.3.16
? update package "weex-builder" now? Yes
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:286:33)
node-pre-gyp ERR! stack     at install (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:165:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:641:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:652:10)
node-pre-gyp ERR! stack     at Module.load (module.js:560:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:503:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:495:3)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
```

**Comment by DinoDom** [comment]
@erha19 Now when I run `weex compile` I got this

```
module.js:544
    throw err;
    ^

Error: Cannot find module 'weex-builder'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/bin/weex.js:89:64)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
```
