### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by unclekitty** [apache/incubator-weex-cli#33]
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/wujun/workspace/weex"
    at /Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/wujun/workspace/weex/wxapp/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/wujun/workspace/weex/wxapp/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/wujun/workspace/weex/wxapp/node_modules/babel-loader/index.js:131:12)
 @ ./src/weex-bootstrap.we?entry=true 2:22-518

**Comment by Jinjiang** [comment]
It this a empty project you generated with `weex init`? Could you please supply more details about your source code or environment? And which command does these error messages come from?
Thanks.

**Comment by Jinjiang** [comment]
Sorry no response for such a long time. I will close it first util you give us more details about your problem.
Thanks.
