### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by imfenghuang** [apache/incubator-weex-cli#332]
```
Vue packages version mismatch:

- vue@2.5.13
- vue-template-compiler@2.5.15
```
重新安装 `npm install -g weex-toolkit`
删除项目中的 `node_modules` 再重新 `npm install`
尝试 ` weex repair`，未发现问题

依然无法解决

尴尬，在解决`weex debug` 无法正确安装后出现了这个上述问题，解决不了了

```
 weex -v
   v1.2.9
 - weex-builder : v0.3.17
 - weex-previewer : v1.4.8
 - toolkit-repair : v0.0.5

node -v
v8.9.4


npm -v
v5.5.1
```

**Comment by erha19** [comment]
@imfenghuang `weex repair` just repair `vue dismatch` in the toolkit, maybe you are using a different version of `vue` and `vue-template-compiler`, try to run `npm i vue@2.5.15 --save` in your project.

**Comment by imfenghuang** [comment]
@erha19 i have installed run 
```
npm i vue@2.5.13 --save
npm i vue-template-compiler@2.5.15 --save
```
but it still not work

**Comment by erha19** [comment]
@imfenghuang you need to install the same version of `vue` and `vue-template-compiler`, it's ruled by vue develop.

**Comment by imfenghuang** [comment]
@erha19 
now, i delete the `node_module` in my project and modified `package.json vue:2.5.4 vue-template-compiler:2.5.4` to the same version, then i run `npm install`

however, it still not work

so sad

**Comment by imfenghuang** [comment]
i delete the weex-toolkit `npm uninstall -g weex-toolkit` and  use `nrm use npm`  and then `npm i -g weex-toolkit`

now `weex preview` is ok~ 

before that, i use the `https://registry.npm.taobao.org/`

**Comment by imfenghuang** [comment]
thx @erha19

**Comment by nothing-important** [comment]
i change the nrm to npm(https://registry.npmjs.org/),but it still not work


Vue packages version mismatch:

- vue@2.5.21 (C:\Users\Administrator\.wx\modules\node_modules\_vue@2.5.21@vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.10 (C:\Users\Administrator\.wx\modules\node_modules\_vue-template-compiler@2.6.10@vue-template-compiler\package.json)

is still have something i need to do?

**Comment by erha19** [comment]
@nothing-important try
```
$ weex repair @weex-cli/core@latest
$ weex update @weex-cli/doctor
$ weex doctor
```
same issue here https://github.com/weexteam/weex-toolkit/issues/516.

**Comment by nothing-important** [comment]
when i execute $ weex doctor(on windows)

C:\Users\Administrator\Desktop\weex_app>weex doctor
Error: ENOENT: no such file or directory, stat 'C:\Users\Administrator\My Documents'
    at Object.statSync (fs.js:850:3)
    at AndroidStudio.allLinuxOrWindows (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\android\android-studio.ts:
175:15)
    at AndroidStudio.allInstalled (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\android\android-studio.ts:90:44
)
    at AndroidStudio.latestValid (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\android\android-studio.ts:80:25)

    at new AndroidStudio (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\android\android-studio.ts:75:9)
    at new AndroidSdk (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\android\android-sdk.ts:101:40)
    at new AndroidValidator (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\android\android-workflow.ts:24:34)
    at Doctor.getValidators (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\doctor.ts:51:27)
    at new Doctor (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\src\doctor.ts:46:9)
    at doctor (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\commands\doctor.js:68:35)
    at Command.run (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_doctor@2.0.0-beta.10@@weex-cli\doctor\commands\doctor.js:184:13)
    at Runtime.<anonymous> (C:\Users\Administrator\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.18@@weex-cli\core\src\runtime\run.ts:64:43)
    at Generator.next (<anonymous>)
    at <anonymous> (C:\Users\Administrator\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.18@@weex-cli\core\lib\runtime\run.js:7:71)
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.18@@weex-cli\core\lib\runtime\run.js:3:12)

**Comment by nothing-important** [comment]
![image](https://user-images.githubusercontent.com/23466804/55858037-3ba45b00-5ba1-11e9-962d-efd9dc53e73a.png)
i have two vue-template-compiler , when i delete vue-template-compiler@2.6.10 , so i have same version between vue and vue-template-compiler , but is still have another question
![image](https://user-images.githubusercontent.com/23466804/55858266-d4d37180-5ba1-11e9-8a9b-e2dff18b49bf.png)
@erha19

**Comment by erha19** [comment]
@imfenghuang try `weex install vue-template-compiler@2.5.21`, if it doesn't work, please open a new issue about this, I will deal with it.

**Comment by nothing-important** [comment]
it still doesn't work , so sad

**Comment by erha19** [comment]
@nothing-important try `weex update @weex-cli/doctor` then run `weex doctor` again.

**Comment by nothing-important** [comment]
`C:\Users\Administrator\Desktop\weex_app>weex update @weex-cli/doctor
× Install fail! Error: GET http://registry.npmjs.org/@weex-cli%2Fupdate response 404 status
Error: GET http://registry.npmjs.org/@weex-cli%2Fupdate response 404 status
    at get (C:\Users\Administrator\.wx\core\node_modules\_npminstall@3.20.2@npminstall\lib\get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\.wx\core\node_modules\_co@4.6.0@co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

`
when i execute `weex update @weex-cli/doctor` , need VPN or nothing else?

**Comment by andrei-utkin** [comment]
I have the same problem. I can't to do: 'weex help' or 'weex update @weex-cli/doctor' like @erha19 said over. Does any one found a solution?
UPD:
Problem was solved for me by command. I have executed 'weex help' like was described on https://weex.apache.org/guide/develop/setup-develop-environment.html#install but the right command is 'weex --help'

**Comment by iusn** [comment]
I have the same problem. 
use 
weex preview src/views/home.vue

error
` Build failed, please check the error below:
./src/views/home.vue
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.21 (/Users
ero/.wx/modules/node_modules/_vue@2.5.21@vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/nero/.wx/modules/node_modules/_vue-template-compiler@2.6.10@vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/nero/.wx/modules/node_modules/_vue-template-compiler@2.6.10@vue-template-compiler/index.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/nero/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/parser.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/nero/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/loader.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
 @ ./.temp/home.js 3:12-44`


then i use weex repair vue-template-compiler@2.5.21
`✔ Installed 1 packages
✔ Linked 0 latest versions
✔ Run 0 scripts
✔ All packages installed (used 295ms(network 294ms), speed 188.73kB/s, json 1(55.49kB), tarball 0B)

Start checking package, please wait ...
compelied, cost 0.924s

Repair vue-template-compiler successed!`

then 

`weex preview src/views/home.vue`

the same error like up
