### ISSUE TITLE
weex debug 调试时报错

### ISSUE THREAD

**Issue by imfenghuang** [apache/incubator-weex-cli#334]
```
[WXModalUIModule] alert param parse error java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.taobao.weex.ui.module.WXModalUIModule.toast(WXModalUIModule.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:46)
	at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:48)
	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:191)
	at android.app.ActivityThread.main(ActivityThread.java:5913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```
连上 debug 服务器之后，WXModalUIModule 报错，浏览器里无法出现 toast ，playground 里显示正常

**Comment by erha19** [comment]
@imfenghuang the debug is using to debug `native` on the browser, it's not a true browser environment.

**Comment by imfenghuang** [comment]
@erha19 
ok. thx
