### ISSUE TITLE
Local environment issue for weex-toolkit

### ISSUE THREAD

**Issue by erha19** [apache/incubator-weex-cli#337]
Error: Command failed: pod update
or
Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

Solution: https://stackoverflow.com/questions/38993527/cocoapods-failed-to-connect-to-github-to-update-the-cocoapods-specs-specs-repo?answertab=votes#tab-top.

Issue: https://github.com/weexteam/weex-toolkit/issues/300#issuecomment-370652227

**Comment by erha19** [comment]
Error:：stderr maxBuffer exceeded

Solution:Update your `weexpack` by `weex update weexpack`,  version `1.0.10` have fixed this issue.

Issue:https://github.com/weexteam/weex-toolkit/issues/344

**Comment by dseeker** [comment]
@erha19 still getting maxBuffer error
weex -version   v1.2.9
 - weexpack : v1.1.8
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

```
07:19:45 : Buiding project...
07:20:11 : Run iOS Simulator..
07:20:11 : Launching iPhone 5s...
07:20:12 : Installing build/Build/Products/Debug-iphonesimulator/WeexDemo.app
07:20:14 : Success!
[0] Wait Reload...                                                                     
 95% [1] emittingWait Reload...                                                        
[1] Wait Reload...
[0] Wait Reload...                                                                     
 95% [0] emittingWait Reload...                                                        
[0] Wait Reload...                                                                     
07:59:19 : Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
07:59:19 : Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:325:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:595:20)

```

**Comment by erha19** [comment]
@deseeker see the file change here https://github.com/weexteam/weex-pack/commit/c27283acedcf03d990a195d51fde24f59cf18b1b#diff-8968c62593320351ced6a0ef776ef599, maybe the size of buffer need be extend, you can try to fix it with a lager numbe,  file should be in the `~/.xtoolkit/node_modules/weexpack`.

**Comment by dseeker** [comment]
I changed it to _Infinity_ and it stopped, haven't managed to blow it up yet, thanks!

**Comment by adminparry** [comment]
this problem is already exist
1 openssl upper
2 gem ruby ... last version
3 [!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

**Comment by adminparry** [comment]
ping github.com is timeout 
PING github.com (52.74.223.119): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3




why do this ? DNS?

**Comment by DavisYao88** [comment]
Error:Error: Command failed: pod update
  Cloning into 'master'...
  remote: Counting objects: 2207668, done.        
  remote: Compressing objects: 100% (150/150), done.        
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)

**Comment by Fundebug** [comment]
got the same error after update weexpack:

weex version:

```bash
weex -v
   v1.3.8
 - weexpack : v1.2.4
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```


error information:

```
/bin/sh: pod: command not found
17:02:17 : Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
17:02:17 : Error:Error: Command failed: pod update
/bin/sh: pod: command not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
```

**Comment by fangxiaohua** [comment]
Command failed: npm i ios-deploy --save  --unsafe-perm=true --allow-root

**Comment by erha19** [comment]
@Fundebug you need to install `cocopods`, Chinese doc here https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#ios%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87%E4%BB%85mac%E5%8F%AF%E7%94%A8.

**Comment by codeliu6572** [comment]
@erha19 weex run ios 之后报这个错，请问这是怎么了？webpack版本有关么？
11:39:32 : Error:Error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! weex_base_project@1.0.0 build: `webpack --env.NODE_ENV=common`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the weex_base_project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Codeliu/.npm/_logs/2018-08-22T03_39_32_540Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by cisco08** [comment]
week platform add ios
然后就可以正常使用
week run ios  了

**Comment by shinriyo** [comment]
@cisco08 

`k` -> `x`
You mean `weex run ios` not `week run ios`.
however, I don't know how to pronounce it.
like wix or weeks

**Comment by KimCongMax** [comment]
Error:Error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wwcp-weex-app@1.0.0 build: `webpack --env.NODE_ENV=common`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the wwcp-weex-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimcong/.npm/_logs/2018-09-26T08_47_31_226Z-debug.log

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by KimCongMax** [comment]
@cisco08
Error:Error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wwcp-weex-app@1.0.0 build: `webpack --env.NODE_ENV=common`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the wwcp-weex-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimcong/.npm/_logs/2018-09-26T08_47_31_226Z-debug.log

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by KimCongMax** [comment]
@erha19

Error:Error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wwcp-weex-app@1.0.0 build: `webpack --env.NODE_ENV=common`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the wwcp-weex-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimcong/.npm/_logs/2018-09-26T08_47_31_226Z-debug.log

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by Duanzihuang** [comment]
1、安装ruby【一般mac都自带了】
    curl -sSL https://get.rvm.io | bash -s stable

2、设置gem镜像
     gem sources --add https://gems.ruby-china.com/

3、使用gem安装cocoapods
     sudo gem install cocoapods

4、重新运行 weex run ios 即可

**Comment by wuwuxi** [comment]
Error: Command failed: npm run serve  这个报错 怎么解决

**Comment by ByteHades** [comment]
这个问题该怎么解决呢？
操作系统：Mac 10.14
XCode Version 10.1 (10B61)
weex run ios
Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
17:29:43 : Error:Error: Command failed: npm i ios-deploy --save  --unsafe-perm=true --allow-root
npm WARN checkPermissions Missing write access to /Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy
npm WARN checkPermissions Missing write access to /Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules
npm WARN checkPermissions Missing write access to /Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules
npm ERR! path /Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy'
npm ERR!  { [Error: EACCES: permission denied, access '/Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/Users/renhuanshan/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/renhuanshan/.npm/_logs/2018-11-09T09_29_43_177Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)

**Comment by erha19** [comment]
@renhuanshan permission issue you can try `sudo chmod -R 777 ~/.xtoolkit`, then run the command again.

**Comment by dzhlch** [comment]
I have a try to do it ,but still take the follow error!

localhost:awesome-project cs_mac$ sudo chmod -R 777 ~/.xtoolkit
Password:

localhost:awesome-project cs_mac$ 
localhost:awesome-project cs_mac$ weexpack run ios
14:30:48 : npm run build
Instailling ios-deploy ...
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/weexpack/node_modules
npm ERR! path /usr/local/lib/node_modules/weexpack/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/weexpack/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/weexpack/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/weexpack/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/weexpack/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cs_mac/.npm/_logs/2018-12-07T06_31_13_141Z-debug.log
14:31:13 : Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
14:31:13 : Error:Error: Command failed: npm i ios-deploy --save  --unsafe-perm=true --allow-root
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/weexpack/node_modules
npm ERR! path /usr/local/lib/node_modules/weexpack/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/weexpack/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/weexpack/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/weexpack/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/weexpack/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cs_mac/.npm/_logs/2018-12-07T06_31_13_141Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)

**Comment by loongcheung** [comment]
> @erha19 weex run ios 之后报这个错，请问这是怎么了？webpack版本有关么？
> 11:39:32 : Error:Error: Command failed: npm run build
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! weex_base_project@1.0.0 build: `webpack --env.NODE_ENV=common`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the weex_base_project@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/Codeliu/.npm/_logs/2018-08-22T03_39_32_540Z-debug.log
> 
> ```
> at ChildProcess.exithandler (child_process.js:275:12)
> at emitTwo (events.js:126:13)
> at ChildProcess.emit (events.js:214:7)
> at maybeClose (internal/child_process.js:925:16)
> at Socket.stream.socket.on (internal/child_process.js:346:11)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at Pipe._handle.close [as _onclose] (net.js:554:12)
> ```

请问这个问题怎么解决的

**Comment by ghost** [comment]
```js

Error:Error: Command failed: npm i ios-deploy --save  --unsafe-perm=true --allow-root
npm WARN checkPermissions Missing write access to /Users/zhangyue/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy
npm ERR! path /Users/zhangyue/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/zhangyue/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy'
npm ERR!  { [Error: EACCES: permission denied, access '/Users/zhangyue/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/Users/zhangyue/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/Users/zhangyue/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangyue/.npm/_logs/2019-02-25T03_01_41_218Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
```

**Comment by KimCongMax** [comment]
@erha19 
系统升级到macOS Catalina后 weex run ios 无法运行

错误：
** BUILD FAILED **


The following build commands failed:
	Ld /Users/kimcong/.xtoolkit/node_modules/weexpack/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
(1 failure)
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.4 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimcong/.npm/_logs/2019-10-19T04_58_53_241Z-debug.log

**Comment by hubao2017** [comment]
> @erha19 weex run ios 之后报这个错，请问这是怎么了？webpack版本有关么？
> 11:39:32 : Error:Error: Command failed: npm run build
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! weex_base_project@1.0.0 build: `webpack --env.NODE_ENV=common`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the weex_base_project@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/Codeliu/.npm/_logs/2018-08-22T03_39_32_540Z-debug.log
> 
> ```
> at ChildProcess.exithandler (child_process.js:275:12)
> at emitTwo (events.js:126:13)
> at ChildProcess.emit (events.js:214:7)
> at maybeClose (internal/child_process.js:925:16)
> at Socket.stream.socket.on (internal/child_process.js:346:11)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at Pipe._handle.close [as _onclose] (net.js:554:12)
> ```

请问这个是怎么解决的？
