### ISSUE TITLE
Can't install app to an ios device with `weex run ios` command.

### ISSUE THREAD

**Issue by ekazuki** [apache/incubator-weex-cli#338]
## Development environment
- weex-toolkit verison
```
$ weex -v
   v1.2.9
 - weexpack : v1.1.5
 - weex-debugger : v1.0.7
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6
```
- platform is MacOS High Sierra 10.13.2
- node version
```
$ node -v
v9.5.0
```
- npm version
```
$ npm -v
5.6.0
```

## The key error stack message.
I want to install app to a ios device. But, below error messages is shown when `weex run ios` command. Please help me if there are solutions to fix this error. Also, I tried to do [this proccess](https://github.com/weexteam/weex-toolkit/issues/300#issuecomment-370652227). But, this error isn't solved.
```
~~~~~
? Choose one of the following devices iPhone ios: 6) (10.2.1
00:30:56 : building...
/bin/sh: /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory
00:30:56 : Success!
00:30:56 : Error:Error: Command failed: /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build . Debug
/bin/sh: /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory

    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at _runAppOnDevice (/Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/run/ios.js:498:20)
    at /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/run/ios.js:375:7
    at new Promise (<anonymous>)
    at runApp (/Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/run/ios.js:371:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by erha19** [comment]
@ekazuki please provide the log above this error log, maybe you have some error with `cocopod`,  and you can try this to upgrade your `cocopod` https://github.com/weexteam/weex-toolkit/issues/337.

**Comment by erickyim** [comment]
Yes, we did install `cocoapods`. 

The error occurs at `childprocess.execSync(path.join(__dirname, '../build/lib/cocoapods-build') + ' . Debug', { encoding: 'utf8' })`.

There's no `cocoapods-build` in `weexpack/lib/build/lib/` folder.

./weexpack/lib/build/
├── android.js
├── index.js
├── ios.js
└── web.js

0 directories, 4 files

**Comment by erickyim** [comment]
duplicated #290.

**Comment by ekazuki** [comment]
@erha19 Thank you for response! This is the all log. I can't found error log for `cocoapods`. 
```
~/WeexSample/awesome-app/ 🐚\ weex run ios
13:58:34 : npm run build

> awesome-app@1.0.0 build /Users/endokazuki/WeexSample/awesome-app
> webpack --env.NODE_ENV=common

Hash: c7e498c183494f22e527909a246b16312f1f1526
Version: webpack 3.11.0
Child
    Hash: c7e498c183494f22e527
    Time: 5626ms
            Asset     Size  Chunks                    Chunk Names
     index.web.js   670 kB       0  [emitted]  [big]  index
    vendor.web.js  13.5 kB       1  [emitted]         vendor
       [0] (webpack)/buildin/global.js 509 bytes {0} [built]
       [4] ./.temp/entry.js 614 bytes {0} [built]
       [8] ./.temp/router.js 588 bytes {0} [built]
      [12] ./src/index.vue 1.76 kB {0} [built]
      [13] ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3f2a2b1e","scoped":true,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 1.54 kB {0} [built]
      [14] ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3f2a2b1e","scoped":true,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 543 bytes {0} [built]
      [18] ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 272 bytes {0} [built]
      [19] ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-3f2a2b1e","hasScoped":true}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 792 bytes {0} [built]
      [20] multi ./node_modules/phantom-limb/index.js 28 bytes {1} [built]
        + 13 hidden modules
Child
    Hash: 909a246b16312f1f1526
    Time: 5329ms
       Asset     Size  Chunks             Chunk Names
    index.js  73.3 kB       0  [emitted]  index
       [0] ./src/entry.js 268 bytes {0} [built]
       [1] ./src/router.js 507 bytes {0} [built]
       [5] ./src/index.vue 1.77 kB {0} [built]
       [6] ./node_modules/weex-vue-loader/lib/style-loader.js!./node_modules/weex-vue-loader/lib/style-rewriter.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 434 bytes {0} [built]
       [7] ./node_modules/weex-vue-loader/lib/script-loader.js!./node_modules/babel-loader/lib!./node_modules/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 272 bytes {0} [built]
       [8] ./node_modules/weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 419 bytes {0} [built]
        + 3 hidden modules
13:58:42 : Move JSbundle to dist
13:58:42 : start iOS app
============Build Config============
AppName      : WeexApp
Version      : 0.1
BuildVersion : 0.1.0
AppId        : com.alibaba.weex
WeexBundle   : index.js
Ws           : ws://192.168.1.8:8082
CodeSign     :
Profile      :
13:58:42 : If you want to change build config.please modify ios.config.json
13:58:42 : pod update
13:58:42 : Hot Reload socket: ws://192.168.1.8:8082
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/endokazuki/.cocoapods/repos/master fetch origin --progress
  $ /usr/bin/git -C /Users/endokazuki/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/endokazuki/.cocoapods/repos/master reset --hard origin/master
13:58:47 : Reloading page...
  HEAD is now at 4c16bb1d801 [Add] AWSAppSync 2.6.14
Analyzing dependencies
Downloading dependencies
Using SDWebImage (3.7.5)
Using SocketRocket (0.4.2)
Using WeexPluginLoader (0.0.1.9.1)
Using WeexSDK (0.18.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
? Choose one of the following devices iPhone ios: 6) (10.2.1
13:59:12 : building...
/bin/sh: /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory
13:59:12 : Success!
13:59:12 : Error:Error: Command failed: /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build . Debug
/bin/sh: /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory

    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at _runAppOnDevice (/Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/run/ios.js:498:20)
    at /Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/run/ios.js:375:7
    at new Promise (<anonymous>)
    at runApp (/Users/endokazuki/.xtoolkit/node_modules/weexpack/lib/run/ios.js:371:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

And, cocoapods version is latest version.
```
~/WeexSample/awesome-app/ 🐚\ pod --version
1.4.0
```

**Comment by erha19** [comment]
@erickyim @ekazuki I will fix it soon, please wait.

**Comment by erha19** [comment]
@ekazuki @erickyim you are all both run your project on a real device?

**Comment by erickyim** [comment]
Yes.

**Comment by erha19** [comment]
@erickyim The `weex-toolkit` does not support to run ios project on real device now, I suggest you use simulator on Xcode., next version we will support this feature.
