### ISSUE TITLE
Error: Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by obetame** [apache/incubator-weex-cli#34]
每次保存文件都出错退出,终端中就这些信息提示:

```shell
2016-11-18 16:51 node[6764] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-18 16:51 node[6764] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-18 16:51 node[6764] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

然后我需要再去重开`weex index.we`.

我是imac10.10.5i系统

**Comment by jonahfang** [comment]
今天重新安装 weex-toolkit(版本还是0.6.4)，这个问题就好了。也不知道是什么原因好的。
