### ISSUE TITLE
weex plugin plush show error

### ISSUE THREAD

**Issue by nyrf** [apache/incubator-weex-cli#361]
```
❯ weex -v
   v1.3.2
 - weexpack : v1.2.0
 - weex-builder : v0.3.19
 - weex-previewer : v1.5.0

❯ npm -v
4.1.2

❯ node -v
v7.5.0
```

after run `weex plugin publish`

```
❯ undefined:106
     ... 18 more items ],
            ^^^^

SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at evaluate (/Users/nyrf/.nvm/versions/node/v7.5.0/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/util/eval.js:10:14)
    at Socket.npm.stdout.on.data (/Users/nyrf/.nvm/versions/node/v7.5.0/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/installer/npm_update_checker.js:55:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

**Comment by erha19** [comment]
@nyrf Do not use `weex plugin publish`, it can't be work now, if you want to publish your plugin with weex's way, you can see the document here https://github.com/weexteam/weex-pack/blob/master/doc/en/how-to-devloping-weex-plugin.md#publish.
