### ISSUE TITLE
初始化项目异常：Error: Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by wzlee** [apache/incubator-weex-cli#363]
`➜  github node -v
v9.11.1
➜  github npm -v
5.6.0
➜  github weex create awesome-project
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@1.0.3@xtoolkit/lib/installer/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)`

**Comment by erha19** [comment]
@wzlee Please provide your `weex` version, run `weex -v` and show me the log.

**Comment by zhaiduo** [comment]
+1  weex -v 也是上面的错，新装

Error: Cannot find module 'inquirer'

node: v8.4.0

**Comment by zhoufengjob** [comment]
+1  npm install -g weex-toolkit

node: v9.10.0 


module.js:545
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@1.0.3@xtoolkit/lib/installer/index.js:1:80)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by zhaiduo** [comment]
works at node 7.9.0

**Comment by erha19** [comment]
@zhaiduo @wzlee @zhoufengjob @k06a
I found this to be related to the strange dependency installation of the `npm5+` version,  there are many `Cannot find module` issues here [npm/issues/16991](https://github.com/npm/npm/issues/16991). 

You can downgrade to use` npm4` to fix this problem, and I've also provided tips on the latest tool versions.

Thanks.

**Comment by erisu** [comment]
I also recall seeing a similar issue, at one point, but it was fixed after reinstalling my node environment... I had other issues not related to weex which required me to do a clean install anyways.

```
$ node -v
v9.11.1

$ npm -v
5.8.0

$ weex -v
   v1.3.4
 - weexpack : v1.2.3
 - weex-builder : v0.3.19
 - weex-previewer : v1.5.0

Warning: npm 5 is not supported yet!

It looks like you're using npm 5 which was recently released.
Weex Toolkit doesn't work well with npm 5 yet, unfortunately.

We recommend using npm 4 until some bugs are resolved.
To install npm 4, you can just run `npm i npm@4 -g` or use `n` to manage your npm version with node.
You can follow the known issues with npm 5 at https://github.com/npm/npm/issues/16991
```

I have not tested all commands, since my update, but `weex run ios` ran perfectly OK with no issues.

**Comment by erha19** [comment]
@erisu yes, the local package dependencies can easily create mismatches with remote package dependencies, like sha256..., that cause many problems while you update package from an old version.
