### ISSUE TITLE
some errors when i create weex project

### ISSUE THREAD

**Issue by ZhanweiXing** [apache/incubator-weex-cli#378]
when i create weex project with the command :'weex create myproject' occors some errors as follow:
SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at evaluate (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/util/eval.js:10:14)
    at Socket.npm.stdout.on.data (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/installer/npm_update_checker.js:55:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
i can't find the reason of these errors.
## my development environment

weex -v :v1.3.3
node -v ：v8.11.1
npm -v: v4.6.1

**Comment by erha19** [comment]
@ZhanweiXing please provide your `weexpack` version.
