### ISSUE TITLE
npm run ios error

### ISSUE THREAD

**Issue by busyhe** [apache/incubator-weex-cli#387]
```
12:59:40 : If you want to change build config.please modify ios.config.json
12:59:40 : pod update
12:59:40 : Hot Reload socket: ws://192.168.0.12:8080
/bin/sh: pod: command not found
12:59:40 : Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
12:59:40 : Error:Error: Command failed: pod update
/bin/sh: pod: command not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
busyhe@localhost:weex-demo$ weex -v
   v1.3.5
 - weexpack : v1.2.3
 - weex-debugger : v1.0.12
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

```

**Comment by busyhe** [comment]
sudo gem install cocoapods
