### ISSUE TITLE
启动ios模拟器时报错

### ISSUE THREAD

**Issue by shekang** [apache/incubator-weex-cli#397]
17:16:13 : npm run build

> weex-pro@1.0.0 build /Users/work_place/weex-pro
> webpack --env.NODE_ENV=common

(node:31054) ExperimentalWarning: The fs.promises API is experimental
Hash: 43a8ed477ce723952bf8a1ee8cbbc11ba4b2aa1b
Version: webpack 3.12.0
Child
    Hash: 43a8ed477ce723952bf8
    Time: 14194ms
            Asset     Size  Chunks                    Chunk Names
     index.web.js   693 kB       0  [emitted]  [big]  index
    vendor.web.js  13.5 kB       1  [emitted]         vendor
       [0] (webpack)/buildin/global.js 509 bytes {0} [built]
       [4] ./.temp/entry.js 612 bytes {0} [built]
       [8] ./.temp/router.js 586 bytes {0} [built]
      [12] ./src/index.vue 1.75 kB {0} [built]
      [13] ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2e922672","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 1.55 kB {0} [built]
      [14] ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2e922672","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 574 bytes {0} [built]
      [18] ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 272 bytes {0} [built]
      [19] ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-2e922672","hasScoped":true}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 859 bytes {0} [built]
      [20] multi ./node_modules/phantom-limb/index.js 28 bytes {1} [built]
        + 13 hidden modules
Child
    Hash: a1ee8cbbc11ba4b2aa1b
    Time: 9177ms
       Asset     Size  Chunks             Chunk Names
    index.js  73.2 kB       0  [emitted]  index
       [0] ./src/entry.js 266 bytes {0} [built]
       [1] ./src/router.js 505 bytes {0} [built]
       [5] ./src/index.vue 1.76 kB {0} [built]
       [6] ./node_modules/weex-vue-loader/lib/style-loader.js!./node_modules/weex-vue-loader/lib/style-rewriter.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 434 bytes {0} [built]
       [7] ./node_modules/weex-vue-loader/lib/script-loader.js!./node_modules/babel-loader/lib!./node_modules/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 272 bytes {0} [built]
       [8] ./node_modules/weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 419 bytes {0} [built]
        + 3 hidden modules
17:16:31 : Move JSbundle to dist
17:16:31 : start iOS app
============Build Config============
AppName      : WeexApp
Version      : 0.1
BuildVersion : 0.1.0
AppId        : com.alibaba.weex
WeexBundle   : index.js
Ws           : ws://192.168.226.128:8080
CodeSign     : 
Profile      : 
17:16:31 : If you want to change build config.please modify ios.config.json
17:16:32 : pod update
17:16:32 : Hot Reload socket: ws://192.168.226.128:8080
Update all pods
Updating local specs repositories
  5% [1] compiling(node:31057) ExperimentalWarning: The fs.promises API is experimental
 10% [1] building modules 0/1 modules 1 active ...sers/work_place/weex-pro/src/entry.js  $ /usr/bin/git -C /Users/shekang/.cocoapods/repos/master fetch origin --progress
 55% [1] Wait Reload...                                             [0]   remote  remote: Counting objects: 450, done.                                         s
  remote: Compressing objects: 100% (97/97), done.        
  remote: Total 450 (delta 210), reused 187 (delta 187), pack-reused 164        
  Receiving objects: 100% (450/450), 55.36 KiB | 0 bytes/s, done.
  Resolving deltas: 100% (255/255), completed with 92 local objects.
  From https://github.com/CocoaPods/Specs
     421cb51..1d0a448  master     -> origin/master
  $ /usr/bin/git -C /Users/shekang/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/shekang/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 1d0a448 [Add] MINTemp 0.0.1
Analyzing dependencies
Downloading dependencies
Using SDWebImage (3.7.5)
Using SocketRocket (0.4.2)
Using WeexPluginLoader (0.0.1.9.1)
Using WeexSDK (0.18.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
? Choose one of the following devices iPhone 6 Plus ios: 9.3 (Simulator)
17:19:43 : Buiding project...
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/work_place/weex-pro/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/WeexSDK.build/Objects-normal/x86_64/WXConvert.o WeexSDK/ios/sdk/WeexSDK/Sources/Utility/WXConvert.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
17:20:05 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=E02B2BC0-CB12-43F9-83C6-BC0BDEE018D4 -sdk iphonesimulator -derivedDataPath build clean build
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/work_place/weex-pro/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/WeexSDK.build/Objects-normal/x86_64/WXConvert.o WeexSDK/ios/sdk/WeexSDK/Sources/Utility/WXConvert.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at checkExecSyncError (child_process.js:596:11)
    at Object.execSync (child_process.js:633:13)
    at _buildOnSimulator (/Users/shekang/.xtoolkit/node_modules/weexpack/lib/run/ios.js:330:18)
    at /Users/shekang/.xtoolkit/node_modules/weexpack/lib/run/ios.js:302:7
    at new Promise (<anonymous>)
    at buildApp (/Users/shekang/.xtoolkit/node_modules/weexpack/lib/run/ios.js:291:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by erha19** [comment]
@shekang I have no idea of this issue, maybe you can try to run your project on `XCode`, and find some detailed log on the terminal console.

**Comment by shekang** [comment]
![screenshot](https://user-images.githubusercontent.com/13003498/40339706-3b632654-5dae-11e8-834e-a3310abf0eca.png)
@erha19

**Comment by erha19** [comment]
@shekang maybe your `XCode` version is old, try to upgrade it to the latest version.
