### ISSUE TITLE
安装weex-toolkit失败

### ISSUE THREAD

**Issue by icepy** [apache/incubator-weex-cli#40]
谁给看看，错误信息如下：

```
➜  weex git:(dev) sudo npm install -g weex-toolkit
npm WARN peerDependencies The peer dependency vue-template-compiler@^2.0.0 included from vue-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency vue-template-compiler@^2.0.0 included from weex-vue-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> spawn-sync@1.0.15 postinstall /Users/xiangwenwen/.nvm/versions/node/v4.6.0/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> fsevents@1.0.17 install /Users/xiangwenwen/.nvm/versions/node/v4.6.0/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/xiangwenwen/.nvm/versions/node/v4.6.0/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> weex-previewer@1.0.5 postinstall /Users/xiangwenwen/.nvm/versions/node/v4.6.0/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

/Users/xiangwenwen/.nvm/versions/node/v4.6.0/lib/node_modules/weex-toolkit/node_modules/weex-previewer/src/libs/fs-utils.js:24
  let exists = fs.existsSync(src);
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/xiangwenwen/.nvm/versions/node/v4.6.0/lib/node_modules/weex-toolkit/node_modules/weex-previewer/src/hook/post-install.js:4:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/xiangwenwen/.nvm/versions/node/v4.6.0/bin/node" "/Users/xiangwenwen/.nvm/versions/node/v4.6.0/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! weex-previewer@1.0.5 postinstall: `node ./src/hook/post-install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-previewer@1.0.5 postinstall script 'node ./src/hook/post-install.js'.
npm ERR! This is most likely a problem with the weex-previewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/hook/post-install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-previewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls weex-previewer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiangwenwen/opensource/weex/npm-debug.log
```

node 版本 v4.6.0
npm 版本 v.2.15.9

**Comment by JackPu** [comment]
@icepy  建议您升级的node(>=6)环境，目前我们在准备发新版，建议您先使用
``` 
npm install weex-toolkit@0.6.4 -g
```

我们这边新版功能确定后，会通知您的。

谢谢亲的支持！💐😄

**Comment by icepy** [comment]
thx
