### ISSUE TITLE
安装1.3.8的版本，执行weex命令报错

### ISSUE THREAD

**Issue by wuchengithub** [apache/incubator-weex-cli#417]
## Your development environment
npm 6.1.0
node 8.11.3
weex 1.3.8
platform mac

## The key error stack message.
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.exports.homePath (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/util/index.js:36:19)
    at Object.exports.modulePath (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/util/index.js:40:29)
    at new NpmPackage (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/package/NpmPackage.js:17:36)
    at Function.getInstance (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/package/index.js:22:12)
    at new Command (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/Command.js:15:30)
    at XToolkit.command (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/lib/xtoolkit.js:134:53)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/bin/weex.js:118:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

执行weex命令报错

**Comment by erha19** [comment]
@wuchengithub maybe you should re-install your toolkit，before you re-install it，we suggest you using `npm@4` by `npm i npm@4 -g`.

**Comment by erha19** [comment]
Issue activity is too low, close
