### ISSUE TITLE
weex-toolkit安装一直报错, checksum签名不一致

### ISSUE THREAD

**Issue by JasonZengJ** [apache/incubator-weex-cli#420]
node版本：尝试过6.2.0、8.11.0、10.5.0 都报错

sudo  npm install weex-toolkit -g --registry=https://registry.npm.taobao.org
Password:
events.js:167░░░░░░⸩ ⠸ extract:mime-types: sill extract argparse@1.0.9
      throw er; // Unhandled 'error' event
      ^

Error: sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= integrity checksum failed when using sha1: wanted sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= but got sha512-60gd675ifiRaKPRQs4WAVcuGq8/0RBo+437RIb3ntk7YpkaCodpoz50spRzm0Va1IeeqREEDJFrzmV0rb+R/RQ== sha1-/+ilNOOiF4sxz+hIStX1zXMfE8Q=. (296 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
events.js:167░░░░░░⸩ ⠏ extract:supports-color: sill extract component-emitter@1.2.1
      throw er; // Unhandled 'error' event
      ^

Error: sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= integrity checksum failed when using sha1: wanted sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= but got sha512-60gd675ifiRaKPRQs4WAVcuGq8/0RBo+437RIb3ntk7YpkaCodpoz50spRzm0Va1IeeqREEDJFrzmV0rb+R/RQ== sha1-/+ilNOOiF4sxz+hIStX1zXMfE8Q=. (296 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
events.js:167░░░░░░⸩ ⠹ extract:slice-ansi: sill extract is-number@2.1.0
      throw er; // Unhandled 'error' event
      ^

Error: sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= integrity checksum failed when using sha1: wanted sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= but got sha512-60gd675ifiRaKPRQs4WAVcuGq8/0RBo+437RIb3ntk7YpkaCodpoz50spRzm0Va1IeeqREEDJFrzmV0rb+R/RQ== sha1-/+ilNOOiF4sxz+hIStX1zXMfE8Q=. (296 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
events.js:167░░░░░░⸩ ⠦ extract: sill extract extsprintf@1.3.0
      throw er; // Unhandled 'error' event
      ^

Error: sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= integrity checksum failed when using sha1: wanted sha1-7PKzJFMi7v04QJ/7iZ4NAAP6b+k= but got sha512-60gd675ifiRaKPRQs4WAVcuGq8/0RBo+437RIb3ntk7YpkaCodpoz50spRzm0Va1IeeqREEDJFrzmV0rb+R/RQ== sha1-/+ilNOOiF4sxz+hIStX1zXMfE8Q=. (296 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: JSONStream@1.3.1 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/JSONStream):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cancel after 1 retries!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cancel after 1 retries!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inline-source-map@0.6.2 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/inline-source-map):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cancel after 1 retries!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lodash._getnative@3.9.1 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/lodash._getnative):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cancel after 1 retries!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/fsevents-6cd1b148/node_modules/wrappy' -> '/usr/local/lib/node_modules/.staging/wrappy-95fbf817'

npm ERR! cancel after 1 retries!
^C

**Comment by erha19** [comment]
@JasonZengJ Firstly, do not use `sudo` command to install a npm package anymore.

To fix this issue, you just need to delete the file on `/usr/local/lib/node_modules/npm/node_modules/weex-toolkit`, and run `sudo chmod -R 777 /usr/local/lib/node_modules/npm/node_modules/` (cause of the npm do not have enough permission to operate it), then run the install command again.

A second easy way is to use `npm@4`, it will not have this issue.

**Comment by erha19** [comment]
If still has some problem, please reopen this issue.

**Comment by JasonZengJ** [comment]
@erha19  first way not work... , the file` /usr/local/lib/node_modules/npm/node_modules/weex-toolkit` is not exist , but there are still checksum problem.

I tried the second way with npm version `4.6.1`,  I got this 

weextest npm install -g weex-toolkit --registry=https://registry.npm.taobao.org
npm ERR! not a package /var/folders/0j/gfvtcgbx5_d7_hg_gxrl4sk80000gn/T/npm-64919-c1928285/github.com/component/emitter/archive/1.0.1.tar.gz
npm ERR! not a package /var/folders/0j/gfvtcgbx5_d7_hg_gxrl4sk80000gn/T/npm-64919-c1928285/github.com/component/emitter/archive/1.0.1.tar.gz
⸨░░░░░░░░░░░░░░░░░░⸩ ⠦ loadRequestedDeps: ERR! not a package /var/folders/0j/gfvtcgbx5_d7_hg_gxrl4sk80000gn/T/npm-64919-c1928285/github.com/component/emitter/archive/1.0.1.tar.gz
