### ISSUE TITLE
安装 beta 版本报错

### ISSUE THREAD

**Issue by hirokith** [apache/incubator-weex-cli#45]
按照 [官方文档](https://weex-project.io/cn/guide/index.html) 执行 `tnpm i -g weex-toolkit@beta` 报错：

```
wx-test ➤ tnpm install -g weex-toolkit@beta                                                                                   
> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall
-
> fsevents@1.0.17 install /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> weex-previewer@1.1.8 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./build/hook/post-install.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/typeof'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/hook/post-install.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Darwin 16.3.0
npm ERR! node v6.9.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! weex-previewer@1.1.8 postinstall: `node ./build/hook/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weex-previewer@1.1.8 postinstall script 'node ./build/hook/post-install.js'.
npm ERR! This is most likely a problem with the weex-previewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build/hook/post-install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-previewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls weex-previewer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hongshu/dev/gitlab/wx-test/npm-debug.log
```

```
wx-test ➤ tnpm -v                                                                                                             git:daily/0.1.0*
tnpm@2.28.1 (/usr/local/lib/node_modules/tnpm/bin/tnpm)
npm@2.15.11 (/usr/local/lib/node_modules/tnpm/node_modules/.2.15.11@npm/lib/npm.js)
node@6.9.2 (/usr/local/bin/node)
npminstall@2.16.0 (/usr/local/lib/node_modules/tnpm/node_modules/.2.16.0@npminstall/lib/index.js)
prefix=/usr/local (load prefix from: $ npm config get prefix)
darwin x64 16.3.0
```

**Comment by JackPu** [comment]
@dickeylth  这个问题最新版本已经修复了，你可以再重新尝试下，

**Comment by hirokith** [comment]
OK，更新后安装不报错了

**Comment by JackPu** [comment]
@dickeylth  哈哈，感谢理解和支持 💐。
