### ISSUE TITLE
very dirty? too much errors.

### ISSUE THREAD

**Issue by cybermerlin** [apache/incubator-weex-cli#451]
node 10.4
npm 6.1
win.10

`weex build android --sacktrace --debug`
```
01:14:38 : Building app ...

> Configure project :app 
WARNING: Configuration 'compile' is obsolete and has been replaced w
ith 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: htt
p://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.0) is i
gnored, as it is below the minimum supported version (27.0.3) for An
droid Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.0'" from y
our build.gradle file, as each version of the Android Gradle Plugin
now has a default version of the build tools.
Error: Command failed: call gradlew.bat  assembleRelease
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* Where:
Build file 'R:\yummm\platforms\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot set the value of read-only property 'outputFile' for ApkVar
iantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, fil
ters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOu
tputImpl.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
 or --debug option to get more log output. Run with --scan to get fu
ll insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at C:\Users\cyber\.xtoolkit\node_modules\weexpack\lib\build\andr
oid.js:156:20
    at new Promise (<anonymous>)
    at buildApp (C:\Users\cyber\.xtoolkit\node_modules\weexpack\lib\
build\android.js:152:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Error: Command failed: call gradlew.bat  assembleRelease
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* Where:
Build file 'R:\yummm\platforms\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot set the value of read-only property 'outputFile' for ApkVar
iantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, fil
ters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOu
tputImpl.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
 or --debug option to get more log output. Run with --scan to get fu
ll insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s


```

weex playground
```
09-11 01:05:55.396 663-663/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendStickyBroadcast:1377 android.net.MobileDataStateTracker$MobileDataStateReceiver.broadcastDataConnectionStateChanged:290 android.net.MobileDataStateTracker$MobileDataStateReceiver.onReceive:521 android.app.LoadedApk$ReceiverDispatcher$Args.run:798 android.os.Handler.handleCallback:808 
09-11 01:05:55.722 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:modal
09-11 01:05:55.724 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:instanceWrap
09-11 01:05:55.727 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:animation
09-11 01:05:55.731 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:webview
09-11 01:05:55.734 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:navigator
09-11 01:05:55.738 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:stream
09-11 01:05:55.743 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:timer
09-11 01:05:55.747 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:storage
09-11 01:05:55.749 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:clipboard
09-11 01:05:55.752 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:globalEvent
09-11 01:05:55.755 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:picker
09-11 01:05:55.757 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:meta
09-11 01:05:55.760 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:webSocket
09-11 01:05:55.763 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:locale
09-11 01:05:55.765 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:render
09-11 01:05:55.767 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:event
09-11 01:05:55.770 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:syncTest
09-11 01:05:55.774 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:myModule
09-11 01:05:55.778 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:geolocation
09-11 01:05:55.781 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:titleBar
09-11 01:05:55.785 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:wsonTest
09-11 01:05:55.788 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:tool
09-11 01:05:55.791 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:toolError
09-11 01:05:55.818 6988-7005/com.alibaba.weex E/weex: [WXBridgeManager]invokeRegisterModules METHOD_REGISTER_MODULES success module:dom
09-11 01:05:56.068 6877-6877/? W/dalvikvm: VFY: unable to resolve virtual method 10149: Landroid/app/NotificationManager;.getNotificationChannelGroups ()Ljava/util/List;
09-11 01:05:56.085 6877-6877/? E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method erd.b
09-11 01:05:56.085 6877-6877/? W/dalvikvm: VFY: unable to resolve new-instance 1982 (Landroid/app/NotificationChannel;) in Lerd;
09-11 01:05:57.045 663-673/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1219 com.android.server.TelephonyRegistry.broadcastDataConnectionStateChanged:869 com.android.server.TelephonyRegistry.notifyDataConnection:623 com.android.internal.telephony.ITelephonyRegistry$Stub.onTransact:157 android.os.Binder.execTransact:404 
09-11 01:05:57.069 663-678/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1219 com.android.server.TelephonyRegistry.broadcastDataConnectionStateChanged:869 com.android.server.TelephonyRegistry.notifyDataConnection:623 com.android.internal.telephony.ITelephonyRegistry$Stub.onTransact:157 android.os.Binder.execTransact:404 
09-11 01:05:57.075 862-1213/? E/CellLocation: create GsmCellLocation
```

**Comment by erha19** [comment]
@cybermerlin have you change the file on `platform/android`, I am not sure what's happening with your android project. maybe some config was not correct, look s `R:\yummm\platforms\android\app\build.gradle' line: 24`.
