### ISSUE TITLE
RequestError: Error: getaddrinfo ENOENT gm.mmstat.com

### ISSUE THREAD

**Issue by eshao731** [apache/incubator-weex-cli#504]
- Downloading template from weex-templates/webpack repo15:52:54 : RequestError: Error: getaddrinfo ENOENT gm.mmstat.com gm.mmstat.com:80
    at new RequestError (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request-promise-core@1.1.1@request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request-promise-core@1.1.1@request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request-promise-core@1.1.1@request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request@2.88.0@request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request@2.88.0@request\request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
15:52:54 : RequestError: Error: getaddrinfo ENOENT gm.mmstat.com gm.mmstat.com:80
    at new RequestError (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request-promise-core@1.1.1@request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request-promise-core@1.1.1@request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request-promise-core@1.1.1@request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request@2.88.0@request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (D:\nodejs\node_global\node_modules\weex-toolkit\node_modules\_request@2.88.0@request\request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
![image](https://user-images.githubusercontent.com/31184871/51966355-3e9b1500-24a7-11e9-819b-e682e9020020.png)

**Comment by eshao731** [comment]
![image](https://user-images.githubusercontent.com/31184871/51966529-b9643000-24a7-11e9-803c-724876dcc992.png)

**Comment by erha19** [comment]
@eshao731 try `weex config telemetry false`.
