### ISSUE TITLE
新安装weex-toolkit后，运行weex debug src报错

### ISSUE THREAD

**Issue by HarryFight** [apache/incubator-weex-cli#509]
新安装weex-toolkit版本如下：

```
$ weex -v
2.0.0-beta.2
- @weex-cli/generator : v2.0.0-beta.3
- @weex-cli/debug : v2.0.0-beta.3
- @weex-cli/compile : v2.0.0-beta.2
```

运行 weex debug src 后报错信息如下：

```
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.21
- vue-template-compiler@2.6.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/harryxiang/.wx/modules/node_modules/_vue-template-compiler@2.6.8@vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/harryxiang/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/parser.js:2:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/harryxiang/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/loader.js:10:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
 @ ./src/router.js 16:12-35
 @ ./src/entry.js

```

根据报错信息，是vue和vue-template-compiler不匹配。
查了对应目录下 vue-template-compiler 是一个软连接到 _vue-template-compiler@2.6.8@vue-template-compiler。 修改软连接到 _vue-template-compiler@2.5.21@vue-template-compiler 后重新执行 weex debug src，还是报上面的错误。

请问这个需要如何处理。

**Comment by erha19** [comment]
@HarryFight 项目内运行一下 `npm i vue-template-compiler@2.5.21 --save`, 然后重新运行。

**Comment by HarryFight** [comment]
@erha19 
按你的方式执行如下：
~/work/cmShow/my-project-weex$ npm i vue-template-compiler@2.5.21 --save
```

npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none was installed.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.

+ vue-template-compiler@2.5.21
updated 1 package in 4.096s
```

~/work/cmShow/my-project-weex$ weex debug src

```
./src/index.vue
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.21
- vue-template-compiler@2.6.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/harryxiang/.wx/modules/node_modules/_vue-template-compiler@2.6.8@vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/harryxiang/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/parser.js:2:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/harryxiang/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/loader.js:10:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
 @ ./src/entry.js 9:10-32
./src/components/HelloWorld.vue

```

依然不行，没有理解weex debug src执行的时候的依赖是找的哪里，从报错信息里面看读取的依赖路径应该是/Users/harryxiang/.wx/modules/node_modules


于是切换到/Users/harryxiang/.wx目录下执行，安装会失败（而在其他目录中执行安装命令都是OK的）
 ~/.wx/modules$ sudo tnpm i vue-template-compiler@2.5.21

```
npm WARN checkPermissions Missing write access to /Users/harryxiang/.wx/modules/node_modules/weex-template-compiler
npm WARN checkPermissions Missing write access to /Users/harryxiang/.wx/modules/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/node_modules/weex-template-compiler
npm WARN a@1.0.0 No description
npm WARN a@1.0.0 No repository field.

npm ERR! path /Users/harryxiang/.wx/modules/node_modules/weex-template-compiler
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/harryxiang/.wx/modules/node_modules/weex-template-compiler'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by erha19** [comment]
@HarryFight 构建这块的依赖位置是在 `~/.wx/modules/node_modules/@weex-cli/compile` 内，你可以对比一下包版本，或者尝试升`vue`依赖配置解决问题, `npm i vue@2.6.8 --save`.
