### ISSUE TITLE
weex -v 返回 undefined

### ISSUE THREAD

**Issue by Ice-Hazymoon** [apache/incubator-weex-cli#511]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
```
undefined
```
- Detact what's wrong with your environment (Run `weex doctor`)
```
TypeError: Cannot read property 'error' of null
    at Cli.<anonymous> (C:\Users\Hazymoon\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.4@@weex-cli\core\src\cli\cli.ts:188:17)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Hazymoon\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.4@@weex-cli\core\lib\cli\cli.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
- Which platform (Win/Mac/Ubuntu..)
Windowns10

## The key error stack message.
安装成功后执行 `weex -v` 返回 `undefind` 执行其他命令报错

```
C:\Users\Hazymoon\Desktop  
λ npm install -g weex-toolkit@beta -f
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
C:\Users\Hazymoon\AppData\Roaming\npm\weex -> C:\Users\Hazymoon\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex.js
+ weex-toolkit@2.0.0-beta.0
updated 1 package in 12.415s

C:\Users\Hazymoon\Desktop  
λ weex -v
undefined

C:\Users\Hazymoon\Desktop  
λ weex doctor
TypeError: Cannot read property 'error' of null
    at Cli.<anonymous> (C:\Users\Hazymoon\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.4@@weex-cli\core\src\cli\cli.ts:188:17)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Hazymoon\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.4@@weex-cli\core\lib\cli\cli.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by erha19** [comment]
@Ice-Hazymoon my mistakes, try `npm i weex-toolkit@beta -g` again,  I republish the npm package to the `beta` tag.

**Comment by Ice-Hazymoon** [comment]
Thanks. Problem solved
