### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by XMBLDB** [apache/incubator-weex-cli#513]
Cannot find module 'async'

win10 
weex-toolkit@2.0.0-beta.6
node v10.15.1
npm 6.4.1

weex create test
√ Installed 1 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 169ms(network 155ms), speed 15.18kB/s, json 1(2.35kB), tarball 0B)

Start checking package, please wait ...
compelied, cost 3.814s
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\xxx\.wx\modules\node_modules\_@weex-cli_generator@2.0.0-beta.3@@weex-cli\generator\src\render.ts:3:0)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\xxx\.wx\modules\node_modules\_@weex-cli_generator@2.0.0-beta.3@@weex-cli\generator\src\index.ts:4:0)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by jerry-f** [comment]
我也遇到同样的问题 切换了node版本也没有用，还切换了不同的 weex 版本，还是报同样的错误

**Comment by jerry-f** [comment]
尝试了很多种方式， 终于找到了解决的办法： weex install async

**Comment by XMBLDB** [comment]
> 我也遇到同样的问题 切换了node版本也没有用，还切换了不同的 weex 版本，还是报同样的错误
换了1.3.11没这个问题

**Comment by erha19** [comment]
@XMBLDB @jerry-f try `weex repair @weex-cli/generator@latest` to fix this issue.
