### ISSUE TITLE
Weex command  Error: Cannot find module './lib'

### ISSUE THREAD

**Issue by player05** [apache/incubator-weex-cli#530]
Error: Cannot find module './lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/lishen/.wx/modules/node_modules/_@weex-cli_plugin@2.0.0-beta.15@@weex-cli/plugin/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/lishen/.wx/modules/node_modules/_@weex-cli_plugin@2.0.0-beta.15@@weex-cli/plugin/commands/plugin.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by yaochenfeng** [comment]
同样遇到这个问题，有解决吗？
weex -v
```
2.0.0-beta.20 (Core 2.0.0-beta.18)
- @weex-cli/plugin : v2.0.0-beta.15
- @weex-cli/compile : v2.0.0-beta.2
```

**Comment by erha19** [comment]
@yaochenfeng ref #533
