### ISSUE TITLE
Cannot find module './lib'

### ISSUE THREAD

**Issue by yaochenfeng** [apache/incubator-weex-cli#533]
weex plugin create weex-plugin-demo
```
Error: Cannot find module './lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/yaochenfeng/.wx/modules/node_modules/_@weex-cli_plugin@2.0.0-beta.15@@weex-cli/plugin/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```
## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
2.0.0-beta.20 (Core 2.0.0-beta.18)
- @weex-cli/plugin : v2.0.0-beta.15
- @weex-cli/compile : v2.0.0-beta.2
- Detact what's wrong with your environment (Run `weex doctor`)
Cannot find module './lib'
- Which platform (Win/Mac/Ubuntu..)
Mac

**Comment by erha19** [comment]
@yaochenfeng try `weex repair @weex-cli/plugin`.

**Comment by yaochenfeng** [comment]
weex plugin create weex-plugin-demo

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/yaochenfeng/.wx/modules/node_modules/_@weex-cli_plugin@2.0.0-beta.21@@weex-cli/plugin/commands/plugin.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

**Comment by yaochenfeng** [comment]
@erha19 The new bug came into being.

**Comment by erha19** [comment]
@yaochenfeng I have published a new module to fix it, try `weex repair @weex-cli/plugin`, that's an error that only appear on windows, sorry for that.

**Comment by erha19** [comment]
@yaochenfeng try `weex repair && weex update @weex-cli/plugin`.

**Comment by yaochenfeng** [comment]
The bug has been solved. Thank you very much!
