### ISSUE TITLE
weex compile 报错

### ISSUE THREAD

**Issue by VirensCn** [apache/incubator-weex-cli#542]
`PS F:\weex\test> weex -v
2.0.0-beta.25 (Core 2.0.0-beta.26)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.17
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/build : v2.0.0-beta.15
- @weex-cli/plugin : v2.0.0-beta.22
- @weex-cli/compile : v2.0.0-beta.24`

才使用`weex create test`新建的项目，未做任何修改 
使用compile指令编译时报错，提示如图
![R2KQE ~GM5VRFNU$WE9IJBN](https://user-images.githubusercontent.com/9736815/56640237-16394600-66a5-11e9-8d1d-f38e10b31ff1.png)

`× Build failed, please check the error below:
./src/index.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.5.21 (C:\Users\ccqlk-loioi\.wx\modules\node_modules\_vue@2.5.21@vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.10 (C:\Users\ccqlk-loioi\.wx\modules\node_modules\_vue-template-compiler@2.6.10@vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (C:\Users\ccqlk-loioi\.wx\modules\node_modules\_vue-template-compiler@2.6.10@vue-template-compiler\index.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\ccqlk-loioi\.wx\modules\node_modules\_weex-vue-loader@0.7.0@weex-vue-loader\lib\parser.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
 @ ./src/entry.js 9:10-32`

**Comment by erha19** [comment]
@VirensCn Try to run `weex doctor`, that problem will be fixed automatically.

**Comment by VirensCn** [comment]
@erha19 谢谢，正常编译了
