### ISSUE TITLE
npm install -g weex-toolkit@beta，安装输出报错

### ISSUE THREAD

**Issue by harrydengchao** [apache/incubator-weex-cli#55]
我是在Win下启动docker Ubuntu容器内操作的这一切，将win下的目录映射到容器/data目录，然后在此下操作的。
node: v6.9.2
npm:v3.10.9

详细报错信息如下：
root@59e355e9d016:/data# npm install -g weex-toolkit@beta
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall

> weex-previewer@1.2.7 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/root"

> weex-toolkit@1.0.1-beta.5 postinstall /usr/local/lib/node_modules/weex-toolkit
> xtoolkit install weex-builder

fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/root/.xtoolkit'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.exports.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/index.js:29:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:10:10)
    at Command.listener (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:17:9)
/usr/local/lib
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/weex-toolkit/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.9.4-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit@beta"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! weex-toolkit@1.0.1-beta.5 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-toolkit@1.0.1-beta.5 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/npm-debug.log
npm ERR! code 1

**Comment by exolution** [comment]
直接用windows下的cmd操作呗 何必这么麻烦
或者尝试sudo（这种复杂环境下的权限问题 真不确定能不能用）

**Comment by bobsam813** [comment]
@exolution 我已经加了sudo了 还是提示权限不足

Error: EACCES: permission denied, mkdir '/Users/bobsam/.xtoolkit/node_modules'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.exports.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/index.js:33:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:10:10)
    at Command.listener (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:17:9)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit@beta"
npm ERR! node v6.9.5
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! weex-toolkit@1.0.1-beta.5 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-toolkit@1.0.1-beta.5 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bobsam/.npm/_logs/2017-02-10T13_22_20_986Z-debug.log

**Comment by exolution** [comment]
建议 sudo chmod 777 /Users/bobsam/
