### ISSUE TITLE
when “weex create awsome-project”，has “Error: Cannot find module 'minimatch'”

### ISSUE THREAD

**Issue by AnpherZhang** [apache/incubator-weex-cli#581]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
- Detact what's wrong with your environment (Run `weex doctor`)
- Which platform (Win/Mac/Ubuntu..)

## The key error stack message.
D:\robotprojects\AppsByVue>weex create awsome-project
√ Installed 1 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 234ms(network 224ms), speed 11.88kB/s, json 1(2.66kB), tarball 0B)

Start checking package, please wait ...
compelied, cost 49.623s
Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Administrator.MICRO-908120921\.wx\modules\node_modules\_@weex-cli_generator@2.0.0-beta.16@@weex-cli\generator\src\utils\filter.ts:1:0)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by AnpherZhang** [comment]
weex -version
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16

**Comment by AnpherZhang** [comment]
weex doctor
√ Installed 1 packages
√ Linked 5 latest versions
√ Run 0 scripts
√ All packages installed (3 packages installed from npm registry, used 3s(network 3s), speed 24.64kB/s, json 6(24.66kB), tarball 41.29kB)

Start checking package, please wait ...
compelied, cost 7.964s
Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Administrator.MICRO-908120921\.wx\modules\node_modules\_@weex-cli_generator@2.0.0-beta.16@@weex-cli\generator\src\utils\filter.ts:1:0)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by AnpherZhang** [comment]
Weex是凉的吗？求解答TT
