### ISSUE TITLE
iphone device can not run  when input   " weex run ios "

### ISSUE THREAD

**Issue by menchao** [apache/incubator-weex-cli#590]
my xcode is  the  latest  11.1 , input  "weex run ios" ，The following error occurred：
019-10-11 14:48:29.111 ios-deploy[17511:776058] [ !! ] Error 0xe8008014: The executable contains an invalid signature. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
⠧ Lanuching APP - this may take a few seconds^CmenchaodeMacBook-Pro:awesome-app menchao$ 

my xode's  signing certificate  be reset   is  None

**Comment by menchao** [comment]
我的xcode的最新版本为 11.1，当我使用weex run ios  在真机调试时，无法运行，报“ The executable contains an invalid signature”，我发现我的xcode配置被重新更改了导致 signing & Capabilities 下的 Signing Certificate is  None
