### ISSUE TITLE
weex run ios: command failed: pod update

### ISSUE THREAD

**Issue by pmz** [apache/incubator-weex-cli#597]
I'm following the guide at https://weex.apache.org/guide/develop/create-a-new-app.html#develop but running weex run ios doesn't work.

**Error: Command failed: pod update**

```
sinatra-2:recorder pmz$ weex run ios
[✔] Compile JSBundle done
? Select one of the device iPhone 11 (Simulator)
[✔] Start hotreload server done
[✔] Set native config done
[✔] Copy JS source done
[✔] Watch JS source done
⠋ Building APP - this may take a few seconds
Error: Command failed: pod update

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
⠹ Building APP - this may take a few seconds
```

My environment:

```
sinatra-2:recorder pmz$ weex --version
2.0.0-beta.17 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2

sinatra-2:recorder pmz$ pod --version
1.8.4
```

**Comment by pmz** [comment]
Ok, I managed to fix it.. 

I ran: `pod repo add CocoaPods https://github.com/CocoaPods/Specs.git `
