### ISSUE TITLE
Error: Command failed: call gradlew.bat clean assembleDebug

### ISSUE THREAD

**Issue by shylon0719** [apache/incubator-weex-cli#602]
系统：win7 win10
在android studio里能跑，用weex run android 报下面错误：
$ weex run android
* daemon not running; starting now at tcp:5037
* daemon started successfully
Error: Command failed: call gradlew.bat clean assembleDebug

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by YorkShen** [comment]
Windows is never supported officially, use it at your own risk.

The document is pretty clear. https://github.com/apache/incubator-weex#for-windows

**Comment by arifiq** [comment]
Error: Command failed: call gradlew.bat clean assembleDebug

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '14.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)

How can we resolve this , it is not working in windows
