### ISSUE TITLE
mac无论创建新项目还是weex run ios 都报错--Error: Cannot find module 'download-git-repo'

### ISSUE THREAD

**Issue by TomWeJack** [apache/incubator-weex-cli#605]
系统mac 10.15.1
weex版本--> 2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2

Error: Cannot find module 'download-git-repo'
Require stack:
- /Users/twj8023chj/.wx/modules/node_modules/_@weex-cli_generator@2.0.0-beta.16@@weex-cli/generator/lib/index.js
- /Users/twj8023chj/.wx/modules/node_modules/_@weex-cli_generator@2.0.0-beta.16@@weex-cli/generator/index.js
- /Users/twj8023chj/.wx/modules/node_modules/_@weex-cli_generator@2.0.0-beta.16@@weex-cli/generator/commands/create.js
- /Users/twj8023chj/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.31@@weex-cli/core/lib/loaders/module-loader.js
- /Users/twj8023chj/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.31@@weex-cli/core/lib/loaders/command-loader.js
- /Users/twj8023chj/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.31@@weex-cli/core/lib/runtime/runtime.js
- /Users/twj8023chj/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.31@@weex-cli/core/lib/core/builder.js
- /Users/twj8023chj/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.31@@weex-cli/core/lib/index.js
- /Users/twj8023chj/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.31@@weex-cli/core/lib/cli/cli.js
- /usr/local/lib/node_modules/weex-toolkit/lib/cli.js
- /usr/local/lib/node_modules/weex-toolkit/bin/weex.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/twj8023chj/.wx/modules/node_modules/_@weex-cli_generator@2.0.0-beta.16@@weex-cli/generator/src/index.ts:6:0)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/twj8023chj/.wx/modules/node_modules/_@weex-cli_generator@2.0.0-beta.16@@weex-cli/generator/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

**Comment by TomWeJack** [comment]
有人遇到过这个问题吗，weex生态比较差，在Q群还有钉钉问了都没人回答，百度也没有相关问题，Does anyone have this trouble

**Comment by YorkShen** [comment]
@erha19 Have a look?

**Comment by cnryb** [comment]
`download-git-repo` is used by `@weex-cli/generator `
On my mac, it's worked.
Maybe you can try re-install weex cli.
