### ISSUE TITLE
weex run android 失败

### ISSUE THREAD

**Issue by zhangweihong** [apache/incubator-weex-cli#615]
weex run android
[√] Compile JSBundle done
[√] Use HWPCT
[√] Start hotreload server done
[√] Set native config done
[√] Copy JS source done
[√] Watch JS source done
\ Total time: 20.198 secsError: Command failed: call gradlew.bat clean assembleDebug
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by cnryb** [comment]
使用 Android studio 打开生成的安卓工程运行，那里能看到更详细的信息。
