### ISSUE TITLE
debug的时候没有对vue文件引入的js文件做 es6 转码导致无法调试

### ISSUE THREAD

**Issue by Neeeo** [apache/incubator-weex-cli#62]
复现的demo见此：
```vue
<template>
  <div class="wrapper">
    <image :src="logoUrl" class="logo"></image>
    <text class="title">Good!! {{target}}</text>
  </div>
</template>

<style>
  .wrapper { align-items: center; margin-top: 120px; }
  .title { font-size: 48px; }
  .logo { width: 360px; height: 82px; }
</style>

<script>
  import hub from './demo.js';  
  export default {
    data: {
      logoUrl: 'https://alibaba.github.io/weex/img/weex_logo_blue@3x.png',
      target: 'World',
    },
  };
</script>
```

引入的 `demo.js` 内容如下：
```js
export let b = 3;
```

用 `weex debug foo.vue` 能编译过，但在iOS模拟器运行调试的时候就会提示这个错误：
```
Uncaught Error: Uncaught SyntaxError: Unexpected token export
    at Object.<anonymous> (http://192.168.1.28:8088/lib/Runtime.js:238:9)
    at http://192.168.1.28:8088/lib/EventEmitter.js:49:25
    at Array.forEach (native)
    at EventEmitter._emit (http://192.168.1.28:8088/lib/EventEmitter.js:48:22)
    at EventEmitter.emit (http://192.168.1.28:8088/lib/EventEmitter.js:61:19)
    at onmessage (http://192.168.1.28:8088/lib/Runtime.js:93:18)
```

如果去掉对 js的引用就没问题。所用的 weex-toolkit 版本是 1.0.1-alpha ， iOS WeexSDK版本是 0.10

**Comment by exolution** [comment]
weex debug目前确实有这个问题 我正在积极处理 近期发版修复

**Comment by luoyang125024608** [comment]
同样遇到这个问题，持续关注中

**Comment by damnright** [comment]
俩月了，什么时候修复？没法调试

**Comment by ghost** [comment]
@exolution 请问这个问题什么时候能修复？

**Comment by n-sikka** [comment]
Any updates on this issues? still facing this guys. Any help?

**Comment by erha19** [comment]
Please upgrade your `weex-toolkit` to the latest version and run `weex update weex-devtool`.

**Comment by n-sikka** [comment]
@erha19 I did, its now giving me 
```
/home/n1kh1l/.xtoolkit/node_modules/weexpack/node_modules/q/q.js:126
                    throw e;
                    ^

Error: spawn E2BIG
    at _errnoException (util.js:1019:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:494:9)
    at UpdateNotifier.check (/home/n1kh1l/.xtoolkit/node_modules/weexpack/node_modules/update-notifier/index.js:64:2)
    at module.exports (/home/n1kh1l/.xtoolkit/node_modules/weexpack/node_modules/update-notifier/index.js:124:17)
    at checkForUpdates (/home/n1kh1l/.xtoolkit/node_modules/weexpack/src/cli.js:69:24)
    at cli (/home/n1kh1l/.xtoolkit/node_modules/weexpack/src/cli.js:228:5)
    at /home/n1kh1l/.xtoolkit/node_modules/weexpack/src/cli.js:114:16
    at _fulfilled (/home/n1kh1l/.xtoolkit/node_modules/weexpack/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/n1kh1l/.xtoolkit/node_modules/weexpack/node_modules/q/q.js:816:30)
```
```
npm -v
5.3.0
node -v
v8.6.0
```
```
weex -v
   v1.0.9
 - weexpack : v0.4.7-beta.4
 - weex-builder : v0.2.9
 - weex-devtool : v0.3.2-beta.6
 - weex-previewer : v1.3.12
```
