### ISSUE TITLE
weex run android失败

### ISSUE THREAD

**Issue by imallb** [apache/incubator-weex-cli#627]
[√] Compile JSBundle done
? Select one of the device Pixel_2_API_24 (Simulator)
[√] Start hotreload server done
[√] Set native config done
[√] Copy JS source done
[√] Watch JS source done
| Building APP - this may take a few seconds
Error: Command failed: call gradlew.bat clean assembleDebug

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '13.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
| Building APP - this may take a few seconds

如何处理

**Comment by imallb** [comment]
为何weex创建的安卓项目https\://services.gradle.org/distributions/gradle-2.14.1-all.zip版本这么低？

**Comment by pengqiangsheng** [comment]
weex run android
[√] Compile JSBundle done
[√] Use Pixel_3a_API_30_x86 (Simulator)
[√] Start hotreload server done
[√] Set native config done
[√] Copy JS source done
[√] Watch JS source done
/ Error: Command failed: call gradlew.bat clean assembleDebug
Exception in thread "main" java.net.ConnectException: Connection timed out: connect

**Comment by pengqiangsheng** [comment]
同问，如上，我的是`Connection timed out: connect`
