### ISSUE TITLE
xtoolkit install weex-builder报错

### ISSUE THREAD

**Issue by zhenhai0793** [apache/incubator-weex-cli#68]
zhenhaifzhdeMacBook-Pro:bin zhenhai.fzh$ node -v
v7.6.0
zhenhaifzhdeMacBook-Pro:bin zhenhai.fzh$ npm -v
4.1.2
zhenhaifzhdeMacBook-Pro:bin zhenhai.fzh$ sudo npm install -g weex-toolkit@beta
Password:
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex

> fsevents@1.1.1 install /usr/local/lib/node_modules/weex-toolkit/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall

> weex-previewer@1.2.9 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/Users/zhenhai.fzh" 

> weex-toolkit@1.0.1-beta.6 postinstall /usr/local/lib/node_modules/weex-toolkit
> xtoolkit install weex-builder

fs.js:893
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/Users/zhenhai.fzh/.xtoolkit'
    at Object.fs.mkdirSync (fs.js:893:18)
    at Object.exports.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/index.js:29:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:10:10)
    at Command.listener (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:192:7)
    at Command.parseArgs (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:17:9)
    at Module._compile (module.js:571:32)
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit@beta"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! weex-toolkit@1.0.1-beta.6 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weex-toolkit@1.0.1-beta.6 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

**Comment by zhenhai0793** [comment]
后来执行uninstall后再重新安装就ok了。安装时还是带了sudo的。如果不带sudo会出现/usr/local/lib没有写权限的错误。现在还会提示 Error:permission denied.Please apply the write premission to the directory: "/Users/zhenhai.fzh" 但是安装还是成功的。
