### ISSUE TITLE
本机运行 weex ****.we 报错。

### ISSUE THREAD

**Issue by sacrelee** [apache/incubator-weex-cli#71]
SACRELEEs-MacBook-Pro:WeexSource SACRELEE$ weex ui-test.we
fs.js:1089
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EACCES: permission denied, unlink '/Users/SACRELEE/.weex_tmp/weex.html'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at copyFileSync (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:13:10)
    at Object.copySync (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:7)
    at Object.initTemDir (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:78:9)
    at Object.fileFlow (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:64:10)
    at Object.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:59:17)
    at module.exports (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/index.js:186:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/bin/weex-previewer:58:1)
    at Module._compile (module.js:570:32)

不知道问题出在哪里，Toolkit重装过也无效，请问这个问题需要怎么解决呢？

**Comment by JackPu** [comment]
@sacrelee 执行下这个命令吧亲：
``` bash
chmod -R 777 /Users/SACRELEE/.weex_tmp
```

**Comment by sacrelee** [comment]
@JackPu 非常感谢，我明天试试。
