### ISSUE TITLE
安装完weex后运行weex -v命令报错

### ISSUE THREAD

**Issue by chenyi2013** [apache/incubator-weex-cli#76]
安装完weex后运行weex -v命令报错
/Users/kevin/.nvm/versions/node/v5.0.0/lib/node_modules/weex-toolkit/node_modules/.0.2.5@xtoolkit/src/xtoolkit.js:12
class XToolkit {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/kevin/.nvm/versions/node/v5.0.0/lib/node_modules/weex-toolkit/bin/weex:3:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
KevinChendeMacBook-Pro:~ kevin$

**Comment by chenyi2013** [comment]
找到原因了node js的版本不对
