### ISSUE TITLE
weex 命令报错

### ISSUE THREAD

**Issue by xyzlmn** [apache/incubator-weex-cli#79]
xtoolkit.command('compile','npm:weex-builder').locate(require.resolve('weex-builder'));
                                               ^

TypeError: xtoolkit.command(...).locate is not a function
    at Object.<anonymous> (/usr/lib/node_modules/weex-toolkit/bin/weex:7:48)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

在 ubuntu14.04  nodejs V6.9.5&V7.7.2 上都报错

**Comment by exolution** [comment]
重新安装一下weex-toolkit就行了~
