### ISSUE TITLE
weex-toolkit安装失败，issues里面没找到解决方案

### ISSUE THREAD

**Issue by rocwong-cn** [apache/incubator-weex-cli#84]
系统配置：
```
node：v6.10.1
npm：3.10.10
OS：macOS 10.12.3 (16D32)
```
错误信息：
```

localhost:~ Roc$ sudo npm install -g weex-toolkit
Password:
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex

> fsevents@1.1.1 install /usr/local/lib/node_modules/weex-toolkit/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall


> weex-previewer@1.3.6 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/Users/RocWang" 

> xtoolkit@0.2.7 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit
> node ./src/hook/post_install.js

fs.js:923
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/Users/RocWang/.xtoolkit/node_modules'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.exports.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/index.js:44:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/hook/post_install.js:7:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
/usr/local/lib
└── (empty)

npm WARN weex-vue-render@0.2.0 requires a peer of vue@^2.1.5 but none was installed.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! xtoolkit@0.2.7 postinstall: `node ./src/hook/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xtoolkit@0.2.7 postinstall script 'node ./src/hook/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xtoolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/hook/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xtoolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xtoolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/RocWang/npm-debug.log
npm ERR! code 1
```

感谢！！！

**Comment by rocwong-cn** [comment]
执行了 `sudo chmod 777 /Users/RocWang` 仍然不行

**Comment by rocwong-cn** [comment]
执行了 sudo chmod -R  777 /Users/RocWang  可以了。。。。。

**Comment by incon** [comment]
The far less aggressive
```
mkdir -p ~/.xtoolkit/node_modules
chmod -R 777 ~/.xtoolkit
```
worked for me
