### ISSUE TITLE
安装weex-tookit之后，执行weex报错

### ISSUE THREAD

**Issue by ableou** [apache/incubator-weex-cli#98]
直接执行weex
usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/._weex-previewer
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50:23)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:149:36)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

执行weex -v
 v1.0.5
 - weexpack : v0.3.13

**Comment by JackPu** [comment]
重新安装下就好了。

**Comment by ableou** [comment]
重新安装很多次了，重启电脑也不行呢

**Comment by ableou** [comment]
使用的是cnpm install -g weex-toolkit命令

**Comment by ableou** [comment]
用这个装npm install -g weex-toolkit就可以了，是否镜像下载的有问题啊

**Comment by DamonZPF** [comment]
我也出现这种问题 使用了VPN 安装成功

**Comment by to686312** [comment]
权限问题

**Comment by amisare** [comment]
怎么解决

**Comment by JackPu** [comment]
@amisare 重新安装下:
```bash
npm uninstall -g weex-toolkit
npm install -g weex-toolkit
```

**Comment by lidehe** [comment]
@DamonZPF 的方法可行，我今天也遇到这个问题，试了好多次都不行，最后连接VPN再安装，就好了

**Comment by anguer** [comment]
使用了sudo， 还是报错，尝试重装了很多次
![image](https://cloud.githubusercontent.com/assets/16484472/25327001/083b8ffc-2905-11e7-8f5c-92e3cd140c27.png)

**Comment by casperSNSN** [comment]
#重新安装也不行啊 ，用sudo安装也不行，各位大大可有别的解决方式？

**Comment by guoshengwang** [comment]
➜  ~ weex -v
   v1.0.5
 - weex-builder : v0.2.6
➜  ~ weex
/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/_weex-previewer
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50:23)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:149:36)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/_xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
➜  ~                                                                                                                     
差不多的错误,搞不定啊

**Comment by lidehe** [comment]
win10系统之前的安装错误也是这个。我把之前版本的文件全部删除，然后打开VPN，就安装上了。Linux的没试过呢

**Comment by JackPu** [comment]
@anguer 建议不要用 sudo 安装，关于 取消 mac npm 全局模块安装的方法可以看[这里](http://www.jackpu.com/xiao-chu-macxia-npmquan-ju-an-zhuang-shi-yong-sudoming-ling/)

**Comment by JackPu** [comment]
@guoshengwang 你的那个问题重新装下就好了。

**Comment by JackPu** [comment]
@casperSNSN  麻烦贴错误日志？

**Comment by luoei** [comment]
@ableou  这里有解决方法，不知能帮到你不？
[https://github.com/weexteam/weex-toolkit/issues/91](url)

**Comment by ableou** [comment]
解决了，不使用镜像安装就可以了
